### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by InfernoGamingYT** [ZeroNoRyouki/ExtremeReactors2#101]
Ive decided to make a big modpack for singleplayer because I'm bored, I have around 400 or so mods, so I will put a screenshot of them all in here(these are all taken from ones that I've looked up and taken from other modpakcs such as crazy craft). I know it has something to do with Extreme reactors, if possible id like to fix this issue without getting rid of the mod, however if that is the only viable option then I can get rid of it.

[Crash Log](https://pastebin.com/vvnUcur4)

Mods:
![m1](https://user-images.githubusercontent.com/55037851/194779795-8e645eb6-172d-417f-b488-eaffb3a87581.PNG)
![m2](https://user-images.githubusercontent.com/55037851/194779794-5dcf3a26-9bbd-479b-8ca7-46ce880aa498.PNG)

**Comment by ZeroNoRyouki** [comment]
Exception message: java.lang.IllegalArgumentException: Names should be valid for use in a ResourceLocation

You are trying to add a new fuel using the API wrapper but the name you are using is not valid. It should be all in lowercase and composed only by letters and / or numbers
