### ISSUE TITLE
Some mod combinations make Fluidizer unobtainable

### ISSUE THREAD

**Issue by burdoto** [ZeroNoRyouki/ExtremeReactors2#102]
Follow Up to https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/72.

In some modpacks, the Fluidizer may be unobtainable, because all Yellorium is converted to Uranium (in my case, from Immersive Engineering) directly, and thus Yellorium is unobtainable.

**Comment by ZeroNoRyouki** [comment]
If those modpacks disable yellorium they should also change the recipes that use it.
Plese open an issue on the mod pack issue tracker, thank you
Z
