### ISSUE TITLE
JEI still missing bits

### ISSUE THREAD

**Issue by Chinthor** [ZeroNoRyouki/ExtremeReactors2#104]
Some of the items in issue #70 are still problems. Unable to look up the recipe or the uses of a given fluid. Unable to check a machine for all recipes used in it. Would be handy to know just how many reprocessors using different working fluids I'm going to need to make.

And a new problem. The top tier moderators give us a use for Anglesite crystals, but now the crystals are not listed in JEI at all. Not just no indication of where to find them or how to process them. They and their ore might as well be deleted from the game but for the recipe to make Tangerium.

So... how are we supposed to make it?

**Comment by ZeroNoRyouki** [comment]
I'll check the JEI things.

As for Anglesite, the book gives a clear hint of where you will find the ore and you get the crystal by mining the ore

**Comment by Chinthor** [comment]
Sorry for that. Version is 1.18.2-2.0.51
I was able to get some info on top-tier materials by ignoring JEI and looking them up in the creative menu. What I didn't find was any use for silk-touched Anglesite ore. Is it meant to be usable in other mod machines for higher output? Or just use luck/fortune.

All in all, I think a certain amount of standard JEI integration would be useful, and wouldn't require you to expose reactant and moderator properties to the API. Most of us just want a convenient way to look up the inputs and outputs of recipes.

**Comment by ZeroNoRyouki** [comment]
I've linked the existing JEI "recipes" to a figurehead block in each machine (ie: reactants -> reactor controller, coolan/vapor mappings -> fluid ports, etc).

It should be out today or tomorrow.
