### ISSUE TITLE
Induction Coils won't work

### ISSUE THREAD

**Issue by jtechie83** [ZeroNoRyouki/ExtremeReactors2#106]
As title states. After 3 days of combing the internet (your tutorial book sucks major fucking donkey dong, fucken fix it or just take this broken shit down) trying to figure out why none of my designs work, i've come to the conclusion it's just broken. I can build everything fine, and get it running, but the minute i try to add an induction coil to the turbine, it tells me it's not a valid block to be inside the turbine. It doesn't matter WHAT i use. It told me Gold isn't metallic. Iron didn't work, it's own added material, Ludicrite, doesn't work. Position doesn't matter, i've put it at the top, the bottom, the middle, made the turbine horizontal, vertical. I'm at my wits end. Time to uninstall this junk and find a better nuclear mod.

**Comment by ZeroNoRyouki** [comment]
Learn to read, moron
