### ISSUE TITLE
Crash with Emendatus Enigmatica...? And ZCore?

### ISSUE THREAD

**Issue by FooterMan14** [ZeroNoRyouki/ExtremeReactors2#110]
So I've encountered an odd few crashes, and I'm not sure who's mod is at fault here, I suspect some kind of incompatibility with each-other.
So, I get a crash related to Emendatus's included Hammer item, saying it's not present. But removing ExtReactors fixed that, but also showed another crash, that was fixed by removing ZeroCore, along with a succesful start. Updating Forge (43.2.4 > 43.2.6) didn't do anything to fix either crashes. This was after I went ahead and updated most of my older things. Even weirder, downgrading both of your mods don't fix the issue.
Crash with ExtReactors: [latest.log](https://gist.github.com/FooterMan14/52bdf6fac55cb5bab71858cad7e01a21) [crash log](https://gist.github.com/FooterMan14/f3a30c7802dd1557c24f16642dd7d42a)
Crash without ExtReactors: [latest.log](https://gist.github.com/FooterMan14/9ba9b5dcc855656361a571bafaae84be) [crash log](https://gist.github.com/FooterMan14/577fe19ddc216c9bdeb6455013b146a7)
All other mods I updated along with ZCore and ExtReactors, if it helps:
XNet
Waystones
Supplementaries 
RFTBase
Quark
Moonlib
Immersive Engineering
Cooking for blockheads
Botania
Balm

**Comment by XGI223** [comment]
I do not know what the issue is but rolling back ExtremeReactors2 to the 1.19.2-2.0.60 and ZCore to 1.19.2-2.1.30 fixed it for me. could be a temp solution until ZeroNoRyouki or Zcore fix it?

**Comment by BedrockLegends** [comment]
I crashed as well, but I dont have Emendatus in my pack
[crash-2023-03-01_22.06.47-fml.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/10867793/crash-2023-03-01_22.06.47-fml.txt)

**Comment by ZeroNoRyouki** [comment]
Yeah rollback to ZC .30 and ER .60 for now, I'm checking what's going on

**Comment by ZeroNoRyouki** [comment]
For some reason, when I build ZC last night on my main dev box, the jar was not obfuscated. I just pushed out ZC 2.1.32 and ER 2.0.62 to fix this. Please upate.

Have fun
Z

**Comment by FooterMan14** [comment]
Thank you Zero! Have a nice day

**Comment by XGI223** [comment]
upgrading to ZC 2.1.32 and ER 2.0.62 fix this for me thanks for the fast response Zero!
