### ISSUE TITLE
Disabled Yellorite Ore and Still Spawns (1.19.2)

### ISSUE THREAD

**Issue by XRealismX** [ZeroNoRyouki/ExtremeReactors2#114]
I've disabled it within the config and still spawns in the world.
![YOND](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/13025294/db161455-cacd-4f2e-977a-35f90b4dd31b)
[latest.log](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/11844869/latest.log)

**Comment by ZeroNoRyouki** [comment]
Since 1.19-ish worldgen is data driven. Looks for the jsons in data/bigreactors/worldgen and ignore the config file
