### ISSUE TITLE
Extreme reactors crash game

### ISSUE THREAD

**Issue by GmanAtheist** [ZeroNoRyouki/ExtremeReactors2#115]
MC 1.19.2. ExtremeReactors2-1.19.2-2.0.64  and  ZeroCore2-1.19.2-2.1.35. MC crashes immediately.  No idea why. Please help. 
Crash report:
http://www.gmanatheist2022.co.uk/Testarea/MC%201.19.2%20crash%20report%2019-07-2023.txt

**Comment by ZeroNoRyouki** [comment]
From the log you posted:
[20:49:27] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'bigreactors', Expected range: '[43.2.1,49)', Actual version: '43.2.0'
	Mod ID: 'forge', Requested by: 'zerocore', Expected range: '[43.2.1,49)', Actual version: '43.2.0'

You need to update Forge

**Comment by GmanAtheist** [comment]
thanks a bunch.  All good now. Your quick response is appreciated.

**Comment by ZeroNoRyouki** [comment]
You are welcome. Have fun!
