### ISSUE TITLE
Reprocessor crashes client but not server when active

### ISSUE THREAD

**Issue by Fr3shlama** [ZeroNoRyouki/ExtremeReactors2#117]
[crash-2023-07-28_00.12.11-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/12188545/crash-2023-07-28_00.12.11-client.txt)
[crash-2023-07-28_00.09.57-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/12188546/crash-2023-07-28_00.09.57-client.txt)

Logs above

I can build the reprocessor, but as soon as it starts converting cyanite to blutonium my client crashes, witha nd without shaders

the server keeps working and I can join again as soon as the ptocessing is finished

Minecraft Version: 1.20.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.3
Forge: net.minecraftforge:47.1.3

**Comment by ZeroNoRyouki** [comment]
Update Extreme Reactor, there is alredy a fix out.

Please check if there is an updated version of the mod that fix your problem before opening an issue. Thank you.

Have fun
Z
