### ISSUE TITLE
Extreme Reactor for 1.20.1 Power Taps not transfering energy through cables

### ISSUE THREAD

**Issue by Brunnn** [ZeroNoRyouki/ExtremeReactors2#118]
I'm using the latest version of extreme reactors for 1.20.1 (.69), and apparantly, the power tap is not working.
See the images:
![image](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/42523274/042f2e5f-8159-4d56-affb-828543dc6b4a)
The reactor has energy stored in the buffer.

Ive tested with 
Ad astra mod energy cables
Ender IO mod energy cables
None of them transfer energy, neither with the active nor passive power taps.
The only way to make it work is by putting a power bank directly connected with the tap.

**Comment by ZeroNoRyouki** [comment]
Fixed in ZeroCore 2.1.39 and Extreme Reactors 2.0.70 (1.16.5 / 1.18.2 / 1.19.2 / 1.20.1)

Have fun
Z

**Comment by Sakurax64** [comment]
This issue seems to be back on ZeroCore 2.1.40 and Extreme Reactors 2.0.76, running latest version of ATM9.
There is no way to get energy out of the reactor.
