### ISSUE TITLE
Turbine not consuming Vapor

### ISSUE THREAD

**Issue by papaworld** [ZeroNoRyouki/ExtremeReactors2#12]
Like another player posted, the Turbine "deforms". For me the rotor shaft is correct until the multiblock is formed, then all rotor shafts turn 90degress when formed. The turbine operates ok otherwise except it does not consume vapor but will exhaust water infinitely.
![2020-11-28_16 06 51](https://user-images.githubusercontent.com/50890375/100527059-8454c180-3194-11eb-93aa-a53024ba1460.png)
![2020-11-28_16 07 04](https://user-images.githubusercontent.com/50890375/100527062-8880df00-3194-11eb-93e5-2feadf1f1e7a.png)
ThanX

**Comment by ZeroNoRyouki** [comment]
Hi, can you reproduce it every time?

If so, could you do two things for me?
1) try it again with ER 2.0.10. I've put a couple of extra checks in there for the rotor problem
2) could you zip your world and put it somewhere (wetransfer, mediafire, etc) so I could take a loot at it?

thanks!
Z

**Comment by papaworld** [comment]
Yes, reproduced all the time... horizontal or vertical... N/S/E/W... doesn't matter design. Ok, I'll give 2.0.10 a try. TX

**Comment by ZeroNoRyouki** [comment]
What are the Turbine dimensions?
Thanks

**Comment by papaworld** [comment]
A test world... overworld only. BTW: the rotor shaft does the same 90 degrees turn within the coils, not just the blades.

**Comment by ZeroNoRyouki** [comment]
Sorry, I was asking how big is the turbine on the x, y and z axis

**Comment by papaworld** [comment]
Any size... the one shown above is the conventional 7x7x16 horizontal in one chunk with the reactor

**Comment by ZeroNoRyouki** [comment]
I've found the problem and it's now fixed. An update should be out today. More info in #11
