### ISSUE TITLE
Benitoite Ore duplication 

### ISSUE THREAD

**Issue by wraithhawit** [ZeroNoRyouki/ExtremeReactors2#121]
I don't know if breaking benitoite is supposed to drop the ore, but using fortune on it gives multiples of the ore. I'm using version 1.20.1-2.0.71 on ATM9 version 0.65

**Comment by ZeroNoRyouki** [comment]
No it should drop the crystal.

I'll try to post a fix tonight

Thanks for the report
Z

**Comment by ZeroNoRyouki** [comment]
Fixed in 2.0.72
