### ISSUE TITLE
Yellorium can't be converted into a reactant 1.20.1

### ISSUE THREAD

**Issue by 1tt2t3Simon** [ZeroNoRyouki/ExtremeReactors2#123]
I have put yellorium into a fluidizer and liquidized it into liquid yellorium however when i try and pipe it into the reactors fuel reactor port it doesn't accept it. 

When I look up the recipe in the JEI (shown picture) It doesn't have a recipe for the yellorium (reactant) but the other reactants do. Is this a bug?

![2023-09-11_19 56 41](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/133691478/0d4decc9-6554-4907-b2cb-1b52520753bf)

**Comment by ZeroNoRyouki** [comment]
What does JEI show in the fluid slot?
It looks like a recipe problem in that pack

**Comment by 1tt2t3Simon** [comment]
alright.

Should I remove this post? since this isn't relevant?
