### ISSUE TITLE
World Gen

### ISSUE THREAD

**Issue by DinnerBeef** [ZeroNoRyouki/ExtremeReactors2#125]
You are unable to turn off Worldgen. I have tried everything I could think of to turn off the ores from spawning in the world. I tried using KubeJS, Tried Turing it off in your config and tired removing them with a data pack and none of that worked.

Mod Version: ExtremeReactors2-1.20.1-2.0.72
Neo Forge Version: 47.1.76
Minecraft Version: 1.20.1
Zero Core Version: ZeroCore2-1.20.1-2.1.39

**Comment by Mimic0445** [comment]
Same problem here.

Minecraft:     1.19.2
Forge:           43.3.0
Mod:            1.19.2-2.0.71
Zero Core:    1.19.2-2.1.39

**Comment by Mimic0445** [comment]
I made a datapack to disable yellorite ore. It works for me. in 1.19.2.

[ExtremeReactorsNoOre.zip](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/13461710/ExtremeReactorsNoOre.zip)

**Comment by Ingrim4** [comment]
Can confirm this is still an issue for 1.20.1. My guess is that ZeroCore doesn't use the provided biome predicate correctly: https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/c1935485af0e3ee44a415f487d3a76597a853d94/src/main/java/it/zerono/mods/extremereactors/gamecontent/WorldGen.java#L77

Minecraft: 1.20.1
Forge: 47.3.5
Mod: 2.0.83
Zero Core: 2.1.44

**Comment by ZeroNoRyouki** [comment]
That class is a left-over, it's not used anymore. Worldgen is controlled by data packs since 1.18 / 19 if I remember correctly. You need to change the json files with a datapack
