### ISSUE TITLE
Reactor Fuel Injection Port will not accept liquid Yellorium

### ISSUE THREAD

**Issue by TonyMacDonald1995** [ZeroNoRyouki/ExtremeReactors2#127]
The Reactor Fuel Injection Port will not accept liquid Yellorium, though it will accept any other valid liquid fuel. The JEI Fluid <=> Reactants tab shows The recipe for Yellorium (reactant) being blank, as shown in the screenshot. I have tested this in the All the Mods 9 modpack as well as custom CurseForge profile containing only Extreme Reactors and JEI.

<img width="474" alt="image" src="https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/42494088/c896a0ee-a863-4be4-899c-f976839b02f6">

Mod Version: ExtremeReactors2-1.20.1-2.0.73
Neo Forge Version: 47.1.3
Minecraft Version: 1.20.1
Zero Core Version: ZeroCore2-1.20.1-2.1.39

**Comment by ZeroNoRyouki** [comment]
A fluid tag for missing. Fixed in 1.20.1-2.0.74

Thank you
Z
