### ISSUE TITLE
Nether Ores ignore Silk Touch

### ISSUE THREAD

**Issue by SephirothWS** [ZeroNoRyouki/ExtremeReactors2#13]
![Image](https://i.imgur.com/iPgE2nB.png)

Running a Mekanism 10 Digital Miner in the Nether using forge:ores* as my tag filter, got silk touch enabled (right most column under To Mine: ______ displays the status of Silk Touch). Got Benitoite instead of its ore variant.

Extreme Reactors 2 - 1.16.4-2.0.9

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. 
I've fixed it and it should be out in the next release

**Comment by ZeroNoRyouki** [comment]
Fixed in 2.0.13
