### ISSUE TITLE
Blutonium ingot is not burned in the reactor as fuel

### ISSUE THREAD

**Issue by BloodInAs** [ZeroNoRyouki/ExtremeReactors2#131]
minecraft 1.20.1
Modloader version
Forge Version 47.2.1
ExtremeReactors2-1.20.1-2.0.73
Blutonium ingot is not burned in the reactor as fuel
`bigreactors:blutonium_ingot`

**Comment by ZeroNoRyouki** [comment]
Is a Blutonium ingot a source for fuel in your pack? Do you see a message sayng so while hovering over an ingot with the advanced tooltips enabled?

Are you sure that there is no leftover fuel (of a different type) inside the Reactor?

**Comment by ZeroNoRyouki** [comment]
Closing as stale
