### ISSUE TITLE
1.20 No fluids flowing in reactor

### ISSUE THREAD

**Issue by Lucky3228** [ZeroNoRyouki/ExtremeReactors2#133]
No liquids flow into the reactor's liquid fuel port (reinforced). Tried it on pipes from Mekanism and Ender IO

**Comment by ZeroNoRyouki** [comment]
Is the fluid a valid fuel source? Enable the advance tooltips and hover on a bucket of that fluild. If it is you should get a message saying so in the tooltip

**Comment by Lucky3228** [comment]
Perhaps this is due to
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/132

**Comment by ZeroNoRyouki** [comment]
What fluid are you trying to inject?

**Comment by ZeroNoRyouki** [comment]
Closing as stale

**Comment by beejayceejay** [comment]
Broken by ATM9 updating as of January of 2024.

**Comment by ZeroNoRyouki** [comment]
What exactly is broken?

**Comment by beejayceejay** [comment]
Survival extraction of rossinite?? its been discussed and brushed off numerous times on this hub.

**Comment by ZeroNoRyouki** [comment]
It works in survival too:
![2024-03-31_11 47 30](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/87f83c1e-2734-4fff-a80b-d119dafe444a)
![2024-03-31_11 47 35](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/3875548e-f91c-493a-b843-5c93ad25895b)
![2024-03-31_11 47 44](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/d9c48ee5-06be-4d40-a9e4-4cdcd77d6e89)
![2024-03-31_11 47 46](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/4f95a66b-a431-4191-ae53-5d4c0aa5693a)
![2024-03-31_11 47 50](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/7107662/471d085a-fc1e-4790-8ae3-9ac71c01e113)

how are you extracting rossinite from the reactor? Which pipes are you using?

Z
