### ISSUE TITLE
Fluidizer reset progress after new item input

### ISSUE THREAD

**Issue by abdullamu** [ZeroNoRyouki/ExtremeReactors2#140]
just as the title says.. i have observe that everytime MR and pipz add new item to the multiblock the progress of creating new item reset.

MC 1.20.1
lastest version of extreme reactor
ATM 9 modpack.

**Comment by ZeroNoRyouki** [comment]
Fixed in dev

**Comment by abdullamu** [comment]
Thank you kindly giod sir

**Comment by ZeroNoRyouki** [comment]
The fix is out in 1.20.1-2.0.79

Have fun
Z
