### ISSUE TITLE
Allow customizing convertion rate between coolants/vapors

### ISSUE THREAD

**Issue by iijunxz** [ZeroNoRyouki/ExtremeReactors2#150]
This rate is 1:1 now, which means that 1mb coolant is turned into 1mb vapor in the recator. However, this rate isn't necessarily 1:1 in different Mods. For example, In GTM, 1mb water is corresponding to 20mb steam, which makes it inefficient to combine active-cooling reactors with GTM's turbines, discouraging inter-mods intergration.

However, this rate is hard-codded now, so I wonder if it's possible to add a line in config file to enable users to customize it easily.

Thanks for your consideration.

**Comment by ZeroNoRyouki** [comment]
The rate is not hard coded, it can be specified for each coolant/vapor transitions.

See

https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/c1935485af0e3ee44a415f487d3a76597a853d94/src/main/java/it/zerono/mods/extremereactors/api/coolant/TransitionsRegistry.java#L104

or FluidTransitions in

https://github.com/ZeroNoRyouki/ExtremeReactors2/tree/master/modpack-api-wrapper

Z
