### ISSUE TITLE
The configuration file doesn't change the property in the game.

### ISSUE THREAD

**Issue by Luppyn** [ZeroNoRyouki/ExtremeReactors2#151]
I'm playing on version 1.20.1, with mod version 2.0.77. 
In my game, I receive a warning:
"Machine is too large, it may be at most 5 blocks in the x dimension". 
Meanwhile, in my common.toml configuration file:

> 	#Define how Reactors works
	[common.reactor]
		#The maximum valid size of a Reactor in the Y dimension, in blocks.
		#Lower this if your server's players are building ginormous Reactors.
		#Bigger Y sizes have far less performance impact than X/Z sizes.
		#Range: 3 ~ 256
		_**maxReactorHeight = 256**_
		#The maximum valid size of a Reactor in the X/Z plane, in blocks.
		#Lower this if your server's players are building ginormous Reactors.
		#Range: 3 ~ 256
		_**maxReactorSize = 256**_
		#A multiplier for balancing Reactor power production. Stacks with powerProductionMultiplier.
		#Range: 0.5 ~ 100.0
		reactorPowerProductionMultiplier = 1.0

**Comment by ZeroNoRyouki** [comment]
A Basic Reactor has a fixed max size of 5x5x5.
