### ISSUE TITLE
Game Crashes on New Newer NeoForge Builds, not sure if its related to a update or something else

### ISSUE THREAD

**Issue by ModernGamingWorld** [ZeroNoRyouki/ExtremeReactors2#152]
![2024-06-02_21 25 53](https://github.com/ZeroNoRyouki/ExtremeReactors2/assets/75923060/312d7744-bc00-4388-94c0-c73069757a1f)

**Comment by ZeroNoRyouki** [comment]
Nop it's on me. Working on a fix
Z

**Comment by ZeroNoRyouki** [comment]
Fixed in ZeroCore 1.20.6-2.3.2 and Extreme Reactors 1.20.6-2.3.2

Thank you for the report
Have fun
Z
