### ISSUE TITLE
Disabling turbine particles via config also disables advanced tooltip

### ISSUE THREAD

**Issue by Kaeldehta** [ZeroNoRyouki/ExtremeReactors2#153]
The client config uses the same variable for deactivating turbine particles as well as disabling the tooltip.
This means you can either deactivate both or leave them both active.

**Comment by ZeroNoRyouki** [comment]
You are probably the first person to use that option since the first 1.16 release of the mod lol

Thanks for the report.

Fixed in dev

**Comment by ZeroNoRyouki** [comment]
Fixed in ER 1.20.1-2.0.81
