### ISSUE TITLE
Info on Energizer

### ISSUE THREAD

**Issue by droolio** [ZeroNoRyouki/ExtremeReactors2#154]
I can find next to no information on the Energizer multi-block that's in ATM9 modpack. Plus the code here on github seems to be a few versions out of date with the one in that pack (2.0.80).

I'm trying to determine if it's possible to interface ComputerCraft with the Energizer, but the lack of documentation, code or API is making this impossible. Apparently, there's getEnergy() and getEnergyCapacity() available methods on the Energizer FE Power Port block, but it just returns 2147483647.

Also, JEI shows no recipe or icon for the "Energizer Status Display" - what even is it?

**Comment by ZeroNoRyouki** [comment]
Yeah I'm a bit behind updating github but time is scarce...

There is currently no support for CC for the Energizer (no computer port for it). What kind of methods where you looking for exactly? Aside for stuff like capacity, energy stored, etc

A block that will be used to display information on the Energizer surface. But it is not ready yet

**Comment by droolio** [comment]
Honestly, I'm not sure what other methods but assumed getEnergy() and getEnergyCapacity() were available, after iterating the modem face. I could be be mistaken, but they showed up as possible methods - the same as Thermal Expansion cells. I did wonder if a proper computer port was necessary, though.

I've been trying to modify this script, to add the Energizer as a storage for reactor/turbine control (it already supports Mek Induction Matrix and Thermal):

https://gitlab.com/seekerscomputercraft/extremereactorcontrol

Anyway, I understand the lack of time - it's good to know ER is still in development. Hopefully, these new additions are added to the in-game manual one day. (What *is* the 'Energizer Status Display' recipe anyway?)

**Comment by ZeroNoRyouki** [comment]
I would check later but it could be Computer Craft that's using the Forge Energy capability exposed by the energy port on it's own. That would also explain that 2147483647 you are getting for the capacity, that's the max value that can be expressed by the getEnergyStored() method of the capability.

I understand what you are doing, I used to use a similar program when playing. I'll add a computer port with similar methods of the other generators

The Status block is not craftable right now

**Comment by ZeroNoRyouki** [comment]
I've added the Energizer Computer Port in ER 1.20.1-2.0.83 and ER 1.21-2.4.3

It expose the following methods (plut the standard multiblocks ones):
- getActive / setActive
- getEnergyStored
- getEnergyCapacity
- getEnergyIoLastTick
- getEnergyInsertedLastTick
- getEnergyExtractedLastTick
- getEnergyStats
- getEnergyStoredAsText
- getEnergyCapacityAsText
- getEnergyIoLastTickAsText
- getEnergyInsertedLastTickAsText
- getEnergyExtractedLastTickAsText
- getEnergyStatsAsText

Have fun!
Z
