### ISSUE TITLE
Potential issue with conditional CC support recipes

### ISSUE THREAD

**Issue by MuteTiefling** [ZeroNoRyouki/ExtremeReactors2#155]
KubeJS is having trouble parsing your recipes when CC is not installed: https://gist.github.com/MuteTiefling/5c37cfbc3a1d82a6b8ca012b15be56f3

Already reported to KubeJS, however, I feel this may be due to some issues with the conditionals in these recipes. 

Neoforge: 21.0.95
Extreme Reactors: 1.21-2.4.3
KubeJS: 2100.7.0-build.79

**Comment by MuteTiefling** [comment]
A helpful user on KubeJS discord has pointed out it's due to ER using old JSON formats: 

![image](https://github.com/user-attachments/assets/11522760-a990-4058-8482-249649fe3aa9)

**Comment by ZeroNoRyouki** [comment]
Good catch! Seems like I forgot to re-gen that recipe when I ported it to 1.21

Fixed in dev. I will push out an update later today
Z

**Comment by ZeroNoRyouki** [comment]
Fixed in 1.21-2.4.4

**Comment by MuteTiefling** [comment]
awesome, thanks!

**Comment by ZeroNoRyouki** [comment]
You are welcome
