### ISSUE TITLE
Missing texture : Falling particle on reactor and turbine blocks

### ISSUE THREAD

**Issue by ym0ka** [ZeroNoRyouki/ExtremeReactors2#156]
- Falling on blocks used in multiblocks structures for reactors and turbines
- See that the falling particles are missing the correct texture on every block

![image](https://github.com/user-attachments/assets/4d4ec141-5261-4a50-b504-33196d9667d8)

Mod version : 2.4.4

**Comment by oskarbukovsky** [comment]
2.0.84 version too (latest 1.20.1)
![Snímek obrazovky 2024-09-16 223259](https://github.com/user-attachments/assets/397b6a39-a47a-4db7-8d78-d5d93303c746)
![Snímek obrazovky 2024-09-16 223310](https://github.com/user-attachments/assets/e17a1368-f9e4-41ce-8ba8-0555a2065acc)
![Snímek obrazovky 2024-09-16 223251](https://github.com/user-attachments/assets/b15a107b-e93c-41c8-9160-f778f87c58da)

**Comment by ZeroNoRyouki** [comment]
Not happening with ZeroCore 2.1.45 and ER 2.0.84:

![image](https://github.com/user-attachments/assets/89f52881-8804-4a63-b8e9-8a5e0dec2aef)

![image](https://github.com/user-attachments/assets/9cdff76a-f088-49b8-a94b-a4a9fdaec194)

 
![image](https://github.com/user-attachments/assets/713c9d66-cf2d-40ac-96f2-3488d7677ad5)

![image](https://github.com/user-attachments/assets/00da3eaf-e542-47bd-8173-f3eadf5670f1)

You probably need to update ZC
