### ISSUE TITLE
Missing tags on ores, ingots, and storage blocks

### ISSUE THREAD

**Issue by MuteTiefling** [ZeroNoRyouki/ExtremeReactors2#157]
Some ores are missing appropriate block/item tags

Deeslate Yellorite is missing the yellorite/ores tags
![image](https://github.com/user-attachments/assets/e0c5b448-eb76-4930-a0d4-41ea0f05f059)

![image](https://github.com/user-attachments/assets/e77a02e4-735c-46b8-969f-eb70a44dae10)

Anglesite has ores as a block tag, but not item tag. It's also missing an anglesite tag
![image](https://github.com/user-attachments/assets/fff1e8cb-18b6-49be-88ca-761f869f99cd)

Benitoite is in a similar situation to anglesite.

![image](https://github.com/user-attachments/assets/2223e07f-48ff-4244-8517-433578713b12)

**Comment by MuteTiefling** [comment]
Ludicrite, ridiculite, inanite, and insanite are all also missing the `c:ingots` tag
![image](https://github.com/user-attachments/assets/4c8313b0-f2d5-4c73-b5d3-4d6c4a1d6c92)

**Comment by MuteTiefling** [comment]
Looks like all the storage blocks are similarly missing the `c:storage_blocks` item/block tags

Iron for reference: 
![image](https://github.com/user-attachments/assets/093f8651-086a-47a5-9c60-af736f4fd407)

Magnetite as an example, though all appear to share the issue
![image](https://github.com/user-attachments/assets/eb587c86-1525-4742-b042-cc744480c2aa)

**Comment by ZeroNoRyouki** [comment]
Tags added in 1.21.1-2.4.6

Have fun
Z

**Comment by MuteTiefling** [comment]
Super, thanks a bunch :D

**Comment by ZeroNoRyouki** [comment]
You are welcome
