### ISSUE TITLE
Radioactivity and Power Production

### ISSUE THREAD

**Issue by GuitarLamp** [ZeroNoRyouki/ExtremeReactors2#158]
I'm currently using the 2.4.4 version for 1.21 on the All the Mods 10 pack

On both a my own locally hosted server with a few friends and on a singleplayer test world I'm seeing an issue where extreme reactors radioactivity is locked at 100% where I'm sure it usually goes well above that with large reactors. On top of that I'm using a 10x10x8 reactor with 18 fuel rod stacks and only getting about 40k RF/t even with various different configurations of position and materials which seems very atypical for extreme reactors behavior. I don't see anything in the configs that would change the values of power generation either.

**Comment by ZeroNoRyouki** [comment]
If you are talking about the "Fuel Reactivity" value in the controller GUI then no, it can't go over 100% (it's the percentage of fuel present in the fuel rods over the amount of fuel+waste)

**Comment by ZeroNoRyouki** [comment]
You can change power production with this config options:
general \ powerProductionMultiplier
reactor \ reactorPowerProductionMultiplier
turbine \ turbinePowerProductionMultiplier

Z
