### ISSUE TITLE
Registry Object Not Present: bigreactors:energizercomputerport

### ISSUE THREAD

**Issue by Waterspark63** [ZeroNoRyouki/ExtremeReactors2#159]
While playing a modpack, I've noticed a crash between ER2 & Minecolonies, when you try to search for some items in the sawmill (which brings up a list of blocks in the game), it crashes when you search some keywords.
(ie. pa (paper), sp (spruce), da (dark oak planks), not even the whole word, just typing towards something can crash the game).

Something breaks while it's filtering the blocks, or it might be trying to render a non-existent/broken block I think, though I'm not sure. But forge seems to be blaming ER2 for the crash.

MC: 1.20.1
Forge: 47.2.30
Extreme Reactors: 2.0.83
Minecolonies: 1.1.619-BETA
Structurize: 1.0.742
BlockUI: 1.0.156
Multipiston: 1.2.43

Here's the log:
https://gist.github.com/Waterspark63/b4b371612b5be44b8ecf7e7e4b66bbed

I'll also post a issue on Minecolonies side as well, to see if they can add a way to prevent the game from crashing from possible invalid blocks/items (if that's the issue.)

**Comment by ZeroNoRyouki** [comment]
Can't reproduce with only ER
