### ISSUE TITLE
mekanism forces reactor to make "liquid steam" (not reactor steam) and then turbine won't accept 

### ISSUE THREAD

**Issue by gameplays12303** [ZeroNoRyouki/ExtremeReactors2#16]
i tested the mod in creative and notice that if you have mekanism install that mod is seeming to override the reactor forcing it to make liquid steam which the turbine won't accept as fuel

i see two ways to  fixes this  
allow liquid steam as steam in turbine  or only allow reactor steam to fill the reactor steam slot in which after the pipes will move it to the turbine 
 
while i do know a bug already submitted would do 
i have submitted bug with the same similar problem already submitted  before however the devplor seems to never seems to it  

i went this way because the problem is so big it needs to be heard

**Comment by ZeroNoRyouki** [comment]
Thank you for the report.

Let's start with some definitions. When you talk about "liquid steam" what do you mean? A Fluid (in Minecraft / Forge terms) as opposed to a (Mekanism) Gas?

The Turbine you mentioned is my own or the one from Mekanism? What type of fluid ports did you use to connect the two?

**Comment by gameplays12303** [comment]
no this steam comes from me mekanism 
i took the mod out and the reactor work fine put it in so it's seems to be something interacting wrongly
you have to take with the mod of mekanism to get an understanding sorry mine can only go so far

**Comment by ZeroNoRyouki** [comment]
Could you please answer my questions?

What type of Fluid Ports are you using and for doing what? Are you trying to pump steam into an Extreme Reactor Turbine or a Mekanism Turbine ?

Also, what version or ER and Mekanism are you using?

A random fluid tagged as "steam" will be choosen as the steam fluid when the first bit of water is vaporized inside the Reactor, it does not matter what mod it belong too as long as it is a fluid and it's tagged as "steam"

The Forge Fluid Port will emit fluids, so you need a pipe that can handle Forge Fluids.
The Mekanism Fluid Port convert forge fluids to Mekanism Gasses (using one of Mekanism Rotary recipies) and you need a pipe that can handle Mekanism Gasses to transfer it

My Turbine only accept forge fluids so you need to connect a Forge Fluid Port from the Reactor to a Forge Fluid Port on the Turbine. As long as the fluid being inserted is tagged as "steam" the Turbine will accept it. It's not possibile to insert a Mekanism Gas Steam into my Turbine

**Comment by gameplays12303** [comment]
then that is the problem maksim doesn't transport the fluid without changing it to their type of gas in which the turbine does not accept it 
the now makes steam : which the game think is a gas  
the turbine will not accept it and i don't know how to make it accept it that is the problem

**Comment by gameplays12303** [comment]
sorry no clear (draft button )
here are the pictures if you want them 
the liquid steam and steam i think is  from mek  
i believe yours is water vapor 
because the condensing  unit will work with steam 
but your turbine will not 
it will pump out (reactor but but not in reactor
![2020-12-09_12 54 11_2](https://user-images.githubusercontent.com/18382354/101676386-b8e03d00-3a20-11eb-9714-603f1a144f21.png) 

![2020-12-09_12 59 02](https://user-images.githubusercontent.com/18382354/101676374-b4b41f80-3a20-11eb-97d8-6360d00a2ced.png)

![2020-12-09_12 54 15](https://user-images.githubusercontent.com/18382354/101676344-a8c85d80-3a20-11eb-9c14-b18b2fc21f14.png)
![2020-12-09_12 54 18](https://user-images.githubusercontent.com/18382354/101676357-af56d500-3a20-11eb-8091-71d05dedf33d.png)

**Comment by ZeroNoRyouki** [comment]
I'm sorry but I stil don't understand what you are trying to do.

If you want steam for using it in an Extreme Reactor Turbine you have to pump the steam produced by an Extreme Reactors Reactor: use a Forge Fluid Port in output mode in the Reactor, connect to it a pipe that can handle fluids (not gasses!) like the mechanical pipes from Mekanism for example, connect the other side of the pipe to a Forge Fluid Port in the Turbine. You could also pump water out of the Turbine and back into the Reactor in the same way, just switch directions on the ports.

If you want steam in GAS FORM for using in in Mekanism machines or in it's Industrial Turbine you need to use the Mekanism Fluid Port in the Reactor. That port will convert steam in fluid form to steam in gas form. Use a pipe that can handle Menanism gasses, like the Pressurized Tubes from Mekanism.

You can't use a Pressurized Tube on a Forge Fluid Port, it will not work. Likewise, you can't use a machanical pipe to connect a Mekanism Fluid Port to other machines.

**Comment by gameplays12303** [comment]
the problem solved itself mekisan now requires 1.11 forge only 1.7 is available so no bug any longer but that also means your mod is partially useless

**Comment by ZeroNoRyouki** [comment]
You do known that this make even less sense that what you posted before right?

**Comment by gameplays12303** [comment]
i know if you want to make it useful just add your own  pipes
