### ISSUE TITLE
Fully Assembled and Built Reactor not Creating Steam - All The Mods 9

### ISSUE THREAD

**Issue by ghost** [ZeroNoRyouki/ExtremeReactors2#161]
MC Version: 1.20.1
Forge Version: 47.2.20
Pack Version: 0.2.61

I have a fully assembled and constructed reactor with 2 forge fluid ports. One is supplied with water and one is the output. I also have fueled the reactor with uranium ingots and have a solid access input/output slots.
![image](https://github.com/user-attachments/assets/5926784a-0c3e-4975-b03b-97603d413e21)
![image](https://github.com/user-attachments/assets/8200b312-dffa-4ebc-bf03-280140933089)
![image](https://github.com/user-attachments/assets/709ae2ff-f4f7-4b55-9b90-a827713f3f4c)
![image](https://github.com/user-attachments/assets/4aa8c8b0-a345-411b-9192-43573d84dc4e)
![image](https://github.com/user-attachments/assets/10ad2fe3-8e01-4a2c-8964-8c2c9959001d)

(sorry about my weird FOV)

**Comment by ZeroNoRyouki** [comment]
Did you set the control rods insertion rate to 100% ? Maybe by pressing "Scram" in the controller GUI ?

**Comment by ghost** [comment]
yes, and sadly none of that worked. The fuel rods were already at 100%

**Comment by ZeroNoRyouki** [comment]
If you set the control rod insertion rate at 100% no reaction will occurs in the reactor, so no energy / vapor is produced. Reduce the insertion rate

**Comment by ghost** [comment]
it was that simple!?!? Thank you!

**Comment by ZeroNoRyouki** [comment]
yup :)
you are welcome
Z

**Comment by ghost** [comment]
> yup :) you are welcome Z

Hey! sorry for a late reply, but do you know how to get the steam from the reactor to the turbine? both are formed and I've tried many different pipes to no avail, thanks!
