### ISSUE TITLE
Unable to load ER with alpha versions of Mekanism for 1.21.1

### ISSUE THREAD

**Issue by MuteTiefling** [ZeroNoRyouki/ExtremeReactors2#162]
neoforge 21.1.23
ExtremeReactors2-1.21-2.4.5
[crash-2024-08-24_11.23.46-fml.txt](https://github.com/user-attachments/files/16737205/crash-2024-08-24_11.23.46-fml.txt)

**Comment by ZeroNoRyouki** [comment]
Downgrade Mekanism for now.

You are using an alpha version in which they changed how gasses are handled

**Comment by MuteTiefling** [comment]
They're all alphas right now :D What's the latest version you support?

**Comment by whatthedrunk** [comment]
Every mod in ATM10 has updated to the new Mekanism now except this one. If you don't plan to fix soon let me know so I can take it out.

**Comment by ZeroNoRyouki** [comment]
I'm already working on it...

**Comment by ZeroNoRyouki** [comment]
> They're all alphas right now :D What's the latest version you support?

For public builds, the last stable version usually. They changed their capabilities in 10.7.0.55 so any version before that should works

**Comment by ZeroNoRyouki** [comment]
Fixed in 1.21.1-2.4.6
Z

**Comment by MuteTiefling** [comment]
Thanks!

**Comment by ZeroNoRyouki** [comment]
You are welcome
