### ISSUE TITLE
[Crash]: Picking up the Fluidizer Solid Injector and then opening your inventory, crashes your game

### ISSUE THREAD

**Issue by Satherov** [ZeroNoRyouki/ExtremeReactors2#164]
Reproduce
- build a valid Fluidizer with the Fluidizer Solid Injector
- break it again
- the Fluidizer Solid Injector should drop
- pick it up
- if you're in creative mode, you will instantly crash
- if you're in survival mode, you will crash after closing your inventory again

Normal Log: https://mclo.gs/BI0S6Ry
Crash Log: https://mclo.gs/Zsa7wWr
 Video https://github.com/user-attachments/assets/0db6aee7-d8fb-4235-a651-9fb01d375898

**Comment by ZeroNoRyouki** [comment]
Fixed in dev

**Comment by ZeroNoRyouki** [comment]
Fixed in ER 1.21.1-2.4.8 and ZC 1.21.1-2.4.8
