### ISSUE TITLE
Modrinth Page outdated

### ISSUE THREAD

**Issue by Gamephantom** [ZeroNoRyouki/ExtremeReactors2#165]
Hi,

I have seen that Curseforge has a newer version than Modrinth:

Modrinth:
![image](https://github.com/user-attachments/assets/aa52dbbd-40e2-4c4a-ae8b-f2dd73411104)

Curseforge:
![image](https://github.com/user-attachments/assets/fc438dfa-911e-42c0-88b9-7bdf1f71a546)

Could you update the Modrinth page with the newest version, please? :-)
Thank you in advance

**Comment by ZeroNoRyouki** [comment]
Done but I don't see the point of keep doing it in the future since Modrinth is not really used that much from what I can see from my stats.
