### ISSUE TITLE
Missing Storage Blocks tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [ZeroNoRyouki/ExtremeReactors2#169]
The following items are missing the `c:storage_blocks` item and block tags:

Ridiculite Block
Inanite Block
Insanite Block
Ludicrite Block

**Comment by ZeroNoRyouki** [comment]
They are not storage blocks

**Comment by TheBedrockMaster** [comment]
Each of them have the `c:storage_blocks/(whatever they are)` tags. Why would they not have the `c:storage_blocks` tag?

> They are not storage blocks

**Comment by TheBedrockMaster** [comment]
@ZeroNoRyouki True, however they already `c:storage_blocks/{material}`, which they shouldn't have. Those will need to be removed.
