### ISSUE TITLE
Server Crash (Loop)

### ISSUE THREAD

**Issue by KontraM8** [ZeroNoRyouki/ExtremeReactors2#17]
Guess Iam back again.

Its the same Problem as I had before one time in another Version. After putting a Mekanism Pressurized Tube (set to pull) on the Mekanism Passive Fluid Port, the server crashed. Now, by the fact that they are attached, I cant start the Server again, because its force loaded.

Best regards

**Comment by ZeroNoRyouki** [comment]
Could you post the crashlog somewhere?

**Comment by KontraM8** [comment]
sure thing: https://pastebin.com/xRNL2dc4

**Comment by ZeroNoRyouki** [comment]
Uhm it crash while trying to read Mekanism rotary recipes. Have you updated Mekanism or Forge recently?

**Comment by KontraM8** [comment]
I have updated Forge from 1.6 to 1.7, havent had any Problems... only with that?

**Comment by ZeroNoRyouki** [comment]
Looks like they removed or renamed a registry method. I'll look into it

**Comment by KontraM8** [comment]
If I would update Mekanism, It would require Forge 1,11 which isnt avaible on CurseForge yet.

**Comment by ZeroNoRyouki** [comment]
I just tested Mekanism-1.16.4-10.0.17.444 and ER 2.0.13 in a clean instance and connected a pressure pipe from a Mek Port to a Chemical Tank. And it did not crash. So there must be something in your pack that's messing with mc registries
![2020-12-11_19 34 27](https://user-images.githubusercontent.com/7107662/101941236-fcd16e80-3be7-11eb-8b51-e786cd1aa37b.png)

**Comment by ZeroNoRyouki** [comment]
are you using the new curse app?

**Comment by KontraM8** [comment]
I was using the ultimate pipe into a mekanism turbine (5x5x9).. dont know if that makes a Difference, yes Iam using the new Forge Launcher

**Comment by ZeroNoRyouki** [comment]
I've replaced the pipe with an ultimate one but it's still ok.
could you test your pack / world under MultiMC instead of the curse app?

**Comment by KontraM8** [comment]
The World that Iam using is actually on my Server (using CurseForge [only for Mods])

**Comment by ZeroNoRyouki** [comment]
Is your server a, let's say, normal forge server install, or did you use any other software to set it up?

**Comment by KontraM8** [comment]
I downloaded forge from the official site and then procceeded to install it as "server" and afterwards, put it on my server via FileZilla [FTP Access]

**Comment by KontraM8** [comment]
Sooo, I recreated my own Problem again, same Mods etc and it doesnt crash either. So Iam just asking myself, wth happened on my Server to Crash?

**Comment by ZeroNoRyouki** [comment]
There is probably some mods doing something strange on MC classes.

**Comment by KontraM8** [comment]
But how can it be, that we dont run into a Problem, when recreating the Problem, but when I start the Server, once it reaches that Starting Point, it just crashes instantly

**Comment by ZeroNoRyouki** [comment]
Who knows what coremods do.. I've checked with the Forge support team and that method (func_212607_c) exist in Forge 1.16.4-35.1.7 so, basically, the crash don't make any sense.

When you restart the server and get another crash, is it the same crash every time?

**Comment by KontraM8** [comment]
https://pastebin.com/Q1utn6u9 , it looks the same to me.

This is my Server Console on the other Hand:

 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
11.12 20:10:53 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.util.registry.Registry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
11.12 20:10:53 [Server] INFO at it.zerono.mods.extremereactors.gamecontent.multiblock.common.part.fluidport.FluidPortHandlerMekanism.lambda$buildMappings$5(FluidPortHandlerMekanism.java:256) ~[bigreactors:1.16.4-2.0.13] {re:classloading}
11.12 20:10:53 [Server] INFO at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_265] {}
11.12 20:10:53 [Server] INFO at it.zerono.mods.extremereactors.gamecontent.multiblock.common.part.fluidport.FluidPortHandlerMekanism.buildMappings(FluidPortHandlerMekanism.java:252) ~[bigreactors:1.16.4-2.0.13] {re:classloading}
11.12 20:10:53 [Server] INFO at it.zerono.mods.extremereactors.gamecontent.multiblock.common.part.fluidport.FluidPortHandlerMekanism.getFluidMapping(FluidPortHandlerMekanism.java:231) ~[bigreactors:1.16.4-2.0.13] {re:classloading}
11.12 20:10:53 [Server] INFO at it.zerono.mods.extremereactors.gamecontent.multiblock.common.part.fluidport.FluidPortHandlerMekanism.extractChemical(FluidPortHandlerMekanism.java:189) ~[bigreactors:1.16.4-2.0.13] {re:classloading}
11.12 20:10:53 [Server] INFO at it.zerono.mods.extremereactors.gamecontent.multiblock.common.part.fluidport.FluidPortHandlerMekanism.extractChemical(FluidPortHandlerMekanism.java:55) ~[bigreactors:1.16.4-2.0.13] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.api.chemical.ChemicalUtils.extract(ChemicalUtils.java:120) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.api.chemical.IChemicalHandler.extractChemical(IChemicalHandler.java:144) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.common.content.network.transmitter.BoxedPressurizedTube.pullFromAcceptor(BoxedPressurizedTube.java:138) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.common.content.network.transmitter.BoxedPressurizedTube.pullFromAcceptor(BoxedPressurizedTube.java:119) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.common.content.network.transmitter.BoxedPressurizedTube.pullFromAcceptors(BoxedPressurizedTube.java:104) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at mekanism.common.tile.transmitter.TileEntityPressurizedTube.func_73660_a(TileEntityPressurizedTube.java:61) ~[mekanism:10.0.17] {re:classloading}
11.12 20:10:53 [Server] INFO at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
11.12 20:10:53 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
11.12 20:10:53 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by KontraM8** [comment]
This should be the Whole Server log: https://pastebin.com/FrCkt1V6

**Comment by ZeroNoRyouki** [comment]
Test the server again without randompatches please

**Comment by KontraM8** [comment]
doing it right now

**Comment by KontraM8** [comment]
It crashed again. from the server console page: https://pastebin.com/kh1jiGPL
and the crash log: https://pastebin.com/ScR0KC1T

**Comment by ZeroNoRyouki** [comment]
You may have to test mod by mod then, removing one and check if it crashes again. Fun, I known....

**Comment by ZeroNoRyouki** [comment]
Make a backup of your world obviously

**Comment by KontraM8** [comment]
Cant I, in theory, remove ER2, start the Server without it, and then reinstall it?

**Comment by ZeroNoRyouki** [comment]
Yes, you could get the server up that way.
Meanwhile I'm working on a workaround

**Comment by KontraM8** [comment]
Okey, I will remove ER2 and reinstall it. I will keep you up to date.

**Comment by ZeroNoRyouki** [comment]
I've pushed out ER 2.0.14 on curse with a possibile workaround for your problems. It should be available as soon as curse approve it. Give it a go, please

**Comment by KontraM8** [comment]
So, I've tried uninstalling ER2, worked fine, just missing blocks (obv) and it worked fine. Now I reinstalled it, it was able to launch etc. . As soon as I set the Pressure Pipe to Pull again, the Server crashed once again.

I will try it out, as soon as I can download it via CurseForge.

**Comment by ZeroNoRyouki** [comment]
Did you test 2.0.14 in the end?

**Comment by KontraM8** [comment]
Iam testing it right now, as it wasnt avaible before I went to sleep.

**Comment by KontraM8** [comment]
It is working now. The Turbine is getting the Steam from the Reactor without Problems and the Server doesnt crash anymore. I dont know what you changed but thanks for fixing it! :)

**Comment by KontraM8** [comment]
But one Thing which Iam either not seeing or just doesnt exist: A config line, to consider how much Steam the Reactor produces, cause I ramped up the Number from the Power Production but havent seen any considering the Steam output.

**Comment by ZeroNoRyouki** [comment]
Good, glad it worked out. I'm closing this.

Do you really feel the need of a "steam production multiplier"?

**Comment by KontraM8** [comment]
Its just a personal thing considering that the Mekanism Turbine consumes a huge amount of Steam to produce Rf/t. I dont want to annoy you..

**Comment by ZeroNoRyouki** [comment]
Don't worry. I just want to know your perspective

**Comment by KontraM8** [comment]
I'd love to see it, cause I hate building like a 40x40 reactor just so it barely makes enough Steam for a Turbine ( I over exaggerated this on Purpose), but you get my Point. You could also maybe do it so the Power Multiplicator = Steam multiplicator, basically one Option for both?

**Comment by ZeroNoRyouki** [comment]
That could be a possibile solution, but then maybe having better control with two different option will suit more people

**Comment by KontraM8** [comment]
Yeah, thats true. Forcing People isnt a good Idea, gotta give them the choice. I'd say: basically adding a Steam Multiplicator Option then..
