### ISSUE TITLE
Further incompitability with sodium on 1.21

### ISSUE THREAD

**Issue by ghost** [ZeroNoRyouki/ExtremeReactors2#171]
The patch provided for #163  seems to only have somewhat alleviated the issue, and now sodium is complaining about ER.

Steps to reproduce: 
1: have an extreme reactor or turbine that as turned on and running
2: mine a block from the multiblock
3: crash

Dismantling a reactor or turbine that is turned off works fine
Log provided: https://mclo.gs/5IagGuo
Playing ATM10, 0.52
Shaders were not enabled, though issue persists with that too.

**Comment by ZeroNoRyouki** [comment]
Does that happens with a Reactor too? I ask because the log is about the turbine rotor
Thanks
Z

**Comment by ghost** [comment]
Ah my bad misread the timestamp on one of the old crash reports
It is indeed turbine only
Reactor, reprocessor and fluidizer does not have this issue that i can find right now

**Comment by ZeroNoRyouki** [comment]
Then I found the problem in the underlying rotor code. I should be able to push out a fix tonight.

**Comment by ZeroNoRyouki** [comment]
Fixed in ZeroCore / Extreme Reactors 1.21.1-2.4.9
