### ISSUE TITLE
Console commands don't work?

### ISSUE THREAD

**Issue by OoishiSan** [ZeroNoRyouki/ExtremeReactors2#173]
I don't understand how commands from this mod work. What i need to write in the end of:
/er reactants get
/er reaction get
/er coils get
So they could work? And there is no examples for this commands

**Comment by ZeroNoRyouki** [comment]
The registration name of the reactant/reaction/coil. There is also a "list" subcommand of each of those that will output the list of registered reactants/reactions/coils

Also, this is not an issue so next time use the discord server  for things like this.
Thanks
Z

**Comment by OoishiSan** [comment]
> The registration name of the reactant/reaction/coil. There is also a "list" subcommand of each of those that will output the list of registered reactants/reactions/coils
> 
> Also, this is not an issue so next time use the discord server for things like this. Thanks Z

And what do these "registration names" look like? And how to display this "list"?
I'm playing on version 1.19.2 and I only have these commands:
/er reactants get/set
/er reaction get/set
/er coils get/set

**Comment by ZeroNoRyouki** [comment]
Yeah that's too old, I've added "list" in 1.20

You can find the standard registrations that ER does here:

https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/1.19/src/main/java/it/zerono/mods/extremereactors/gamecontent/ReactorGameData.java

https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/1.19/src/main/java/it/zerono/mods/extremereactors/gamecontent/TurbineGameData.java

Have fun
Z
