### ISSUE TITLE
[Visual Bug] Got black&purple particles when breaking turbinerotorshaft and turbinerotorblade

### ISSUE THREAD

**Issue by ArcticAbyss1979** [ZeroNoRyouki/ExtremeReactors2#174]
Pack: ATM9 NoFrills 0.1.14
MCversion: 1.20.1 Forge 47.2.21
Extreme Reactors 2.0.78

**Comment by ZeroNoRyouki** [comment]
ZeroCore version?

**Comment by ArcticAbyss1979** [comment]
> ZeroCore version?

ZeroCore2-1.20.1-2.1.42

**Comment by ZeroNoRyouki** [comment]
Fixed in dev

**Comment by ZeroNoRyouki** [comment]
Fixed in ER 1.20.1-2.0.86

1.21.1 still wip

**Comment by ZeroNoRyouki** [comment]
ZeroCore 1.20.1-2.1.47 / 1.21.1-2.4.13 and Extreme Reactors 1.20.1-2.0.87 / 1.21.1-2.4.13 are now available, featuring a workaround for a (Neo)Forge bug that prevented the display of correct "fall damage" block particles
