### ISSUE TITLE
Lack of wiki

### ISSUE THREAD

**Issue by ThatElektrika** [ZeroNoRyouki/ExtremeReactors2#175]
There is no wiki or patchouli book on the Neoforge version of the mod, please at least create a basic wiki or provide an explanation on how to build an energizer on the mod page.

**Comment by ZeroNoRyouki** [comment]
![image](https://github.com/user-attachments/assets/bc3fab71-b781-467a-aaf6-76e7b4e136a5)

Patchuoli is out for 1.21.1 so I'm re-adding the book for that version

**Comment by ThatElektrika** [comment]
Not my point at all. You need a wiki in case something like this happens, so people can find information without the book if necessary.

**Comment by ZeroNoRyouki** [comment]
Feel free to make one, I've no time to handle that too

**Comment by ThatElektrika** [comment]
I’ll need the base stats for all blocks that are default for the mod then, for coolants, moderators, coils, etc

i couldn’t find this information anywhere including in the old book

**Comment by ZeroNoRyouki** [comment]
They are in the source code
Keep in mind that modpacks and other mods can add/modify/remove registered moderator, coils, reactants, etc using the ER API

**Comment by ThatElektrika** [comment]
unable to find the references as to how different materials get registered (can’t find what the float values are pointing to)

**Comment by ThatElektrika** [comment]
i couldn’t understand the examples for how it works in the main branch so i’m wanting to find the actual code to understand how they work, that way i can attempt to explain the inner workings a bit better

**Comment by ThatElektrika** [comment]
also it appears the repo is a bit outdated, last shown update was last year, did you move to a new repo?

**Comment by ZeroNoRyouki** [comment]
The master branch is 1.16. Check the 1.21 one

Registrations happens here:

https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/1.21/src/main/java/it/zerono/mods/extremereactors/gamecontent/ReactorGameData.java

https://github.com/ZeroNoRyouki/ExtremeReactors2/blob/1.21/src/main/java/it/zerono/mods/extremereactors/gamecontent/TurbineGameData.java

**Comment by ThatElektrika** [comment]
ok ty

**Comment by ThatElektrika** [comment]
…this still doesn’t tell me where the float values are defined, i need to know what each individual float value is for

**Comment by ZeroNoRyouki** [comment]
In the relevant classes in the it.zerono.mods.extremereactors.api package

**Comment by ThatElektrika** [comment]
couldn’t find it

am i just blind?

**Comment by ZeroNoRyouki** [comment]
https://github.com/ZeroNoRyouki/ExtremeReactors2/tree/1.21/src/main/java/it/zerono/mods/extremereactors/api
