### ISSUE TITLE
'machine is too small' message when building the minimal configuration in the book

### ISSUE THREAD

**Issue by TheRealAaronPrince** [ZeroNoRyouki/ExtremeReactors2#178]
building the 3x3x3 reactor shown in the book assembles properly but gives the machine too small error.
if this is intentional behavior then could you update the book to reflect this, especially because it is used as the example for the first reactor for the player to build.

**Comment by ZeroNoRyouki** [comment]
The reactor from the book is a valid basic reactor. 

Could you share some pictures of your setup with the chunk borders turned on? Also, plase cheat in a debug tool from ZeroCore and right client and shift+right click it on a block of the reactor and post here the chat messages you get.

Versions of ER and ZeroCore ?

**Comment by TheRealAaronPrince** [comment]
ER 2.0.71
zero core 2.1.39

it seems to be working now since I've reloaded
and it isn't accross a chunk border. 
if this issue comes back, I'll make sure to check the debug tool.
also I hope I didn't come off as rude, it's just the machine too small message is a little opaque
![Uploading 2024-10-21_19.36.37.png…]()
.

**Comment by ZeroNoRyouki** [comment]
Don't worry
