### ISSUE TITLE
Cannot craft Extreme Book

### ISSUE THREAD

**Issue by uhloin** [ZeroNoRyouki/ExtremeReactors2#179]
Versions:
MC 1.21.1 
Neoforge 21.1.68

Mods:
ExtremeReactors2-1.21.1-2.4.11.jar 
Patchouli-1.21-87-NEOFORGE.jar 
ZeroCore2-1.21.1-2.4.11.jar

**Comment by ZeroNoRyouki** [comment]
Thank you, problem found. I should be able to push an update out tonight.

**Comment by ZeroNoRyouki** [comment]
Fixed in ER 2.4.12
