### ISSUE TITLE
Energizer FE Port doesn't "Push" Forge Energy

### ISSUE THREAD

**Issue by Direwolf20-MC** [ZeroNoRyouki/ExtremeReactors2#182]
Hello :). 

I setup an Energizer, and its receiving energy just fine, but when i set one of the FE ports to 'output mode' its not pushing energy. 

I was able to hack around this because laserIO can do a 'pull' of FE, and that worked. 

Screenshot below, showing cable has 0 FE in it.

![image](https://github.com/user-attachments/assets/62dd3c92-ff19-45bd-8a67-0a2815719478)

**Comment by ZeroNoRyouki** [comment]
Hi there.
Yup, by design it act like a "passive" port of the other multiblocks, so you need cables that can insert and extract on their own. You could have plenty of ports per single energizer and that could hurt TPS a bit if they all auto-extract/insert

**Comment by Direwolf20-MC** [comment]
My understanding is that Forge energy is meant to be a push based system though - so cables that “pull” energy aren’t actually behaving correctly. 

I didn’t know this when I made LaserIO and never removed it :). 

But most cables I tested with don’t have a “pull” option.

**Comment by ZeroNoRyouki** [comment]
Interesting, I was not aware of that either, and there is nothing in the docs about it.

I will add an 'active' FE port that will push energy when in output mode so players can choose which one to use depending on their needs. The Energizer already distributes energy to the charging ports, so it will be straightforward to implement.

**Comment by ZeroNoRyouki** [comment]
Active port added in ER 1.20.1-2.0.90 and 1.21.1-2.4.15

Have fun
Z

**Comment by Direwolf20-MC** [comment]
Thank you! :)

**Comment by andrewsf** [comment]
Note that regarding the screenshot and the notion that LaserIO is special -- Mekanism cables are designed to pull FE. Like pipes/tubes, the Configurator can be used to switch cable ends into push & pull modes. Accordingly, Mekanism energy sources can be configured to _not_ push FE. Another common example would be SuperFactoryManager, which _only_ pulls energy with no option to receive it.

> My understanding is that Forge energy is meant to be a push based system though - so cables that “pull” energy aren’t actually behaving correctly.

Forge Energy is built around the [Redstone Flux API](https://github.com/CoFH/CoFHLib-1.7.10-Legacy/blob/master/src/main/java/cofh/api/energy/EnergyStorage.java), which was designed for energy to be pushed or pulled. The convention of mods choosing to push energy is only that, a convention to help out mods that are not counting their energy intake well.
