### ISSUE TITLE
Error saving state with fuel injection port

### ISSUE THREAD

**Issue by inputTTS** [ZeroNoRyouki/ExtremeReactors2#183]
Hi, so I have a friend on my server who is having issues with the Fuel Injection Port. When she tries to place it, or move the block, it floods the server console with errors. It seems to be that the fluid port is trying to save its state with empty fluid tanks, but the serialization code is rejecting this as invalid? 

[sever log](https://pastebin.com/x0MRYcW0) and this is an ATM10 server minecraft 1.21 modpack version 1.23

**Comment by ZeroNoRyouki** [comment]
Fixed in dev

**Comment by ZeroNoRyouki** [comment]
Fixed in Extreme Reactors 2.4.16 and ZeroCore 2.4.14
