### ISSUE TITLE
Fluidizer Solid Injector not accepting ender pearls

### ISSUE THREAD

**Issue by apdjz** [ZeroNoRyouki/ExtremeReactors2#185]
Extreme Reactors 1.21.1-2.4.15

Fluidizer Solid Injector does accept Anglesite (PbS04) but does not accept ender pearls for some reasons.  

Modpack FTB Evolution 1.30

**Comment by ZeroNoRyouki** [comment]
Works fine with the default recipe:

![{2CF9B317-B74B-4636-9827-90EB7E5F154A}](https://github.com/user-attachments/assets/e6fa19c2-5cf2-4ecb-b4ac-02ade51560e0)

![{92697890-2B51-4B6D-A516-77A28E61D259}](https://github.com/user-attachments/assets/8a29cea1-1868-46c5-8fab-f1244be73139)
