### ISSUE TITLE
Reactor Casings are the only valid block under a Fuel Rod

### ISSUE THREAD

**Issue by bookerthegeek** [ZeroNoRyouki/ExtremeReactors2#188]
## Heyo!

While building my reactor, It was not forming. After testing found out that the reactor will not validate if there is any block under a fuel rod that is not a reactor casing block.

Don't know if that was intended or not.

### Other Information
Minecraft: 1.21.1
NeoForge:  21.1.90
ER2: 1.21.1-2.4.18

Pack: All The Mods 10 - 2.12

**Comment by ZeroNoRyouki** [comment]
Hello
Yes, it's by design.

Have fun
Z
