### ISSUE TITLE
New moderators

### ISSUE THREAD

**Issue by DMNerd** [ZeroNoRyouki/ExtremeReactors2#19]
Hey. I would add them myslef in PR, but I am still a bit fuzzy on the numbers. So for the purposes I am making an Issue for suggesting new moderators for the reactor

Minecraft: Packed Ice (Since in code it is added as minecraft:ice, packed ice won't work?)
Powah: Dry ice - should be better than ice

**Comment by ZeroNoRyouki** [comment]
Thank you for your suggestions.

Unfortunately packed ice is already in the vanilla "ice" tag so it's already covered as a moderator

I've added Powah Dry Ice in a "dry_ice" tag so other similar blocks could be added there

**Comment by ZeroNoRyouki** [comment]
It's included in 2.0.16
