### ISSUE TITLE
Steam reactor shows B/t instead of mB/t

### ISSUE THREAD

**Issue by frank89722** [ZeroNoRyouki/ExtremeReactors2#20]
ExtremeReactors2-1.16.4-2.0.17
ZeroCore2-1.16.4-2.0.16
with default config

This is a  3*3 and 4 blocks tall reinforced reactor
![image](https://user-images.githubusercontent.com/10683361/102910916-4bb7b780-44b6-11eb-8a49-01c2b3727986.png)

And it shows it produces 286B/t of steam

![image](https://user-images.githubusercontent.com/10683361/102910596-c8966180-44b5-11eb-8d94-d02745dbb417.png)

**Comment by 8qBITs** [comment]
how are you pumping water into the reactor?

**Comment by ZeroNoRyouki** [comment]
You can use pipes. Or, in desperate situations, a bucket on a passive fluid port

**Comment by ZeroNoRyouki** [comment]
I've fixed it, thank you for the report. It should be out in the next release
