### ISSUE TITLE
Steam is not consumed when vent is set to Vent excess coolant or do not vent coolant

### ISSUE THREAD

**Issue by Geometer1729** [ZeroNoRyouki/ExtremeReactors2#21]
When the vent mode is set to either, vent only excess coolant or do not vent coolant and the reactor is on steam is not consumed but rpm increases. 

To reproduce this:
- Load up a modpack with just ZeroCore-1.16.4-2.0.16 and ExtremeReactors2-1.16.4.2.0.17
- Create a turbine I suspect any will work but I made a 7x7x7 with 16 gold block coils, 24 blades and a vertical axis
- Manually place 2 buckets of steam into the fluid input
- Set the vent mode to Vent only excess coolant
- Turn the turbine on
What happens for me is, the steam stays at 2B, the Coolant fluid tank fills up and the RPM climbs, if you engage the coils you seem to be able to produce infinite free power.

**Comment by Geometer1729** [comment]
Oh sorry I meant to include the forge version: I'm using 35.1.10

**Comment by ZeroNoRyouki** [comment]
Thank you for the report!
I've fixed it, it should be out in the next release
