### ISSUE TITLE
Using mekanism turbine

### ISSUE THREAD

**Issue by 8qBITs** [ZeroNoRyouki/ExtremeReactors2#22]
How can i use the mekanism turbine along with the reactor as there is only a passive port?

**Comment by ZeroNoRyouki** [comment]
You use pipes to pump gas out of the Mekanism Fluid Port and into the Mek Turbine

**Comment by 8qBITs** [comment]
well turbine needs gas and reactor produces fluid

**Comment by 8qBITs** [comment]
also theres no "active" mekanism port

**Comment by ZeroNoRyouki** [comment]
> well turbine needs gas and reactor produces fluid

That's why you need to use the Mekanism Fluid Port instead of the normal one. It will automatically convert from liquid to gas if a Mek rotary recipe exist for the liquid in the Reactor


> also theres no "active" mekanism port

Yes, you need to pump it out of the port

**Comment by 8qBITs** [comment]
well when i tried it did not output anything

**Comment by ZeroNoRyouki** [comment]
Did you use pipes that supported Mek gasses and autoextraction ?

**Comment by 8qBITs** [comment]
worked now thats weird
