### ISSUE TITLE
Basic recipe for Fluid Port missing

### ISSUE THREAD

**Issue by critchards** [ZeroNoRyouki/ExtremeReactors2#24]
The extreme guidebook shows an entry and graphic for the basic fluid port but only the reinforced variant exists. Not sure if it is intended that the basic fluid port not be included or an oversite?

Recipe for basic fluid port is not registered.
ExtremeReactors2/src/main/java/it/zerono/mods/extremereactors/datagen/recipes/ReactorRecipeGenerator.java

**Comment by ZeroNoRyouki** [comment]
There is no Basic Reactor Fluid Port in the mod (you can't build an actively cooled Basic Reactor) ence no recipe is registered for it.

The guidebook show entries for the generic parts (controller, power taps, fluid ports, etc) and list the variants said parts are available in. The graphics show in the Reactor Fluid Port entry are the ones of the Reinforced Fluid Port.

**Comment by critchards** [comment]
Ohhhh sorry. I looked at the image and thought the Basic Turbine Housing was Basic Reactor Casing. My bad.

![Forge fluid port](https://user-images.githubusercontent.com/22669053/103715298-1e1e4400-4f75-11eb-8ae8-c59e2703288a.png)

**Comment by ZeroNoRyouki** [comment]
No problems!

**Comment by VoidFletcher** [comment]
Just commenting with some feedback here, this definitely feels like a bug from the player's perspective. Is this decision from a balancing standpoint?

I'm currently sitting with some old reactors, and it feels pretty pointless throwing away the old casing, perhaps it would be good to add some form of upgrade path, to upgrade the blocks into their reinforced counterparts?

Keep up the great work!

**Comment by ZeroNoRyouki** [comment]
It's part of the mod progression. The Basic Reactor is there for your early-game almost mid-game power generation. To get serious you need to move to Reinforced Reactors

You can already craft all your Basic parts back to the Basic Casings used to craft them. Basic Casing can then be used to craft Reinforced Casings.
