### ISSUE TITLE
Reactor/Turbine Issue 

### ISSUE THREAD

**Issue by Jimberys** [ZeroNoRyouki/ExtremeReactors2#26]
The fluid ports on both reactor and turbine are not allowing water or steam in or out.
I have the steam setup as import into turbine and output to reactor and have it cycled and the turbine wont turn on.
If I place a creative steam tank into the turbine it works fine, but if I have a creative steam tank out side the turbine and have it connected by pipes the turbine wont turn on,
I also tried to have both reactor and turbine connected with pipes and only the creative steam tank in the turbine. The turbine does turn on but does not let the water through to the reactor.

Can you please check into this thank you !

**Comment by ZeroNoRyouki** [comment]
A couple of questions:

1) ER version?

2) what do you mean by "creative tank" ? ER creative water / steam generators?

3) what kind of pipes are you using to connect the fluid port on the reactor to the fluid port on the turbine?

4) could you post a pic of your setup somewhere and link it here?

thank you
Z

**Comment by Jimberys** [comment]
Version ExtremeReactors2-1.16.4-2.0.19
Turbine creative steam Generator reinforced and Creative fluid tank 
I've tired these pipes Refined pipes- fluid pipes , Cyclic-block fluid pipes, Pretty Pipes, Fluid pipes, Immersive Engineering-fluid pipe, Mekanism- Ultimane Mechanical pipe.
![2021-01-06_12 52 43](https://user-images.githubusercontent.com/77068605/103803131-2b433d80-501e-11eb-82fb-dbd41844f8bb.png)
![2021-01-06_12 52 58](https://user-images.githubusercontent.com/77068605/103803144-2e3e2e00-501e-11eb-88c0-08c3c76a56dd.png)
![2021-01-06_12 41 54](https://user-images.githubusercontent.com/77068605/103803156-31d1b500-501e-11eb-8353-f23288d5fb4f.png)
![2021-01-06_12 42 09](https://user-images.githubusercontent.com/77068605/103803161-34340f00-501e-11eb-8552-104d9916625f.png)

**Comment by Jimberys** [comment]
I took out the Turbine creative steam Generator reinforced to show the water not being accepting by the reactor to make steam

**Comment by ZeroNoRyouki** [comment]
Thank you. I think I've found the problem, you can use Passive Fluid Ports in the meantime as a workaround

**Comment by Jimberys** [comment]
Passive ports don't work either, I'll wait until you have a patch for it, Thank You ! Awesome mod tho

**Comment by ZeroNoRyouki** [comment]
Thank you. When using passive ports you have to configure the pipes to do the work, inserting and extracting fluids

**Comment by ZeroNoRyouki** [comment]
Hi, the fix should be out in the next version

**Comment by Jimberys** [comment]
Awesome Thank You !

**Comment by ZeroNoRyouki** [comment]
The fix is in 2.0.20
