### ISSUE TITLE
Reactor - Fluid Input/Output compatibility (1.12.2)

### ISSUE THREAD

**Issue by BlackDragonX007** [ZeroNoRyouki/ExtremeReactors2#28]
Hello,

I was hoping to use your reactor in my modpack to generate High Temperature Coolant that I then can run through heat exchangers to then use to make Steam (more like IRL nuclear reactors)

Would there be a way to add a compatibility with Immersive Tech's Distilled water to allow that to be the input to the reactor?

Thanks,
BlackDragon

**Comment by ZeroNoRyouki** [comment]
Sure, you can add any fluid as a valid coolant and register a resulting "vapor" fluid for it. Players wil be able to insert the new coolant into an active reactor and pump out the resulting vapor.

Check this doc:

https://github.com/ZeroNoRyouki/ExtremeReactors2/tree/master/modpack-api-wrapper

**Comment by BlackDragonX007** [comment]
You sir are awesome.

**Comment by ZeroNoRyouki** [comment]
You are welcome!

Have fun
Z

**Comment by BlackDragonX007** [comment]
Hey Z,

I've spend the last few hours trying to get this to work but I must be missing something in the way to setup the api file.

I've used Contenttweaker to create two new fluids (hot and cold coolant), I want to run the cold coolant into the reactor and get hot coolant out (to be used by another machine down the line to make Steam and then produce power).
I copied your demo file, edited to what I thought was what I needed, but its behaving like the API file isn't there. (aka, Water -> Steam still happens in the reactor)

any thoughts on next steps?
here's the pastebin to the json file [https://pastebin.com/gdG8MUGW](url)

ps. yes I did remember to enable it.

Thanks,
BlackDragon

**Comment by ZeroNoRyouki** [comment]
Assuming the IDs you used are correct, the file looks OK.

Could you give the me your config for contenttweaker ?

Z

**Comment by BlackDragonX007** [comment]
Here's the script I used to make the fluids, [https://pastebin.com/zMFXPpVB](url).

Or do you want the actual mod configs?

Dragon

**Comment by ZeroNoRyouki** [comment]
I'd like to test it too, so anthing I would need to recreate your setup
Z

**Comment by BlackDragonX007** [comment]
Understood.

Link to the Curseforge export. [https://www.dropbox.com/s/g8v92af2ppxc84r/Testingreactor-1.0.zip?dl=0](url)

Even included the Saves for you so you can see how I've been testing it.

Let me know if that doesn't work, and I'll zip the whole directory up for you and send it that way.


Dragon

**Comment by ZeroNoRyouki** [comment]
Found the problem. You are targeting MC 1.12.

The modpack api wrapper and custom coolants/vapors are features of the 1.16.4 version of ER.

**Comment by BlackDragonX007** [comment]
Anyway to adjust those values on MC 1.12 version as the mod sits now?

**Comment by ZeroNoRyouki** [comment]
Unfortunately no, 1.12 only support water / steam (it's hardcoded in the mod)

**Comment by BlackDragonX007** [comment]
Understood,  Thanks for all your help with this.

**Comment by ZeroNoRyouki** [comment]
This could be the perfect excuse to move to 1.16.4 :)
