### ISSUE TITLE
Turbine Multiblock Maximum Size Issue (5x5x10)

### ISSUE THREAD

**Issue by VoidFletcher** [ZeroNoRyouki/ExtremeReactors2#29]
Hi there!

I'm currently running Extreme Reactors 2 (v2.0.21) as a part of the Direworlf20 pack. It seems the turbine is currently limited in size, and completely ignores config changes.

The current size limit is stuck at 5 blocks on X, 5 blocks on Z, with a maximum height of 10. I recall being able to build the turbine significantly bigger. I've checked the config, both client and server-side, with no luck.

Is this intended?

Additional Notes: I am using the basic turbine.

Thanks!

**Comment by VoidFletcher** [comment]
Some extra notes, changes to the config were in the suggested range - but I also tried with values less than 32 as I recall reading a GitHub post somewhere about that being the hard limit. I don't need the turbine to be huuuuuge, just... not so small :D

**Comment by ZeroNoRyouki** [comment]
Yes, the Basic Turbine is limited to 5x5x10. The Reinforced one is not limited per se and follow the config settings
