### ISSUE TITLE
GUI not showing internal storage max size properly for reactor.

### ISSUE THREAD

**Issue by TheDarkPreacher** [ZeroNoRyouki/ExtremeReactors2#31]
Version: ExtremeReactors-1.16.4-2.0.21
ZeroCore Version: ZeroCore2-1.16.4-2.0.19
Modpack: Direwolf20 1.16, version 1.6.1

I have a 3x3x5 reinforced reactor on my server, and it says the max internal storage is 1MFE, but it says that starting at about 88% storage. Using a CC:Tweaked computer and a LUA script to control the reactor, I found out that the internal buffer was 1.35MFE. It seems that the display cuts off the decimal places in the reactor GUI.

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. I've fixed it in dev. If will be out on the next release (of Zero CORE 2)
