### ISSUE TITLE
Redstone Port - Fuel Richness does not seem to work

### ISSUE THREAD

**Issue by beiai** [ZeroNoRyouki/ExtremeReactors2#32]
Minecraft Version: 1.16.5
forge: 36.0.13
Version: ExtremeReactors-1.16.4-2.0.21
ZeroCore Version: ZeroCore2-1.16.4-2.0.19

I can only get the signal when I set to Active Below 1%.
no matter what the actual reactivity in the reactor.
It seems like the value is always 0?

**Comment by ZeroNoRyouki** [comment]
Thank you for the report! I've fixed it in dev, it should be out in the next release
