### ISSUE TITLE
Redstone Port - a small problem with the GUI showing

### ISSUE THREAD

**Issue by beiai** [ZeroNoRyouki/ExtremeReactors2#33]
Minecraft Version: 1.16.5
forge: 36.0.13
Version: ExtremeReactors-1.16.4-2.0.21
ZeroCore Version: ZeroCore2-1.16.4-2.0.19

The display range of the hover box on the Coolant Amount and Vapor Amount icon is a bit small
for example, The position in the image,  does not show the hover box，By the way, the click range is small too
![2021-02-10_170045](https://user-images.githubusercontent.com/16081195/107487844-935ae580-6bc1-11eb-9c97-bdce282d62f4.png)

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. I've fixed it.
