### ISSUE TITLE
Redstone Port - It seems that the GUI is missing a description

### ISSUE THREAD

**Issue by beiai** [ZeroNoRyouki/ExtremeReactors2#34]
Minecraft Version: 1.16.5
forge: 36.0.13
Version: ExtremeReactors-1.16.4-2.0.21
ZeroCore Version: ZeroCore2-1.16.4-2.0.19

Sorry, me again.
In the language file I see this description
"gui.bigreactors.reactor.redstoneport.sensortype.inputsetcontrolrod.settolevel": "Set the Control Rod insertion level based on the strength of the signal (0 = 0% and 15 = 100%)",
I check the code, It doesn't seem to be used.
In the picture it should be here
![20210210213301](https://user-images.githubusercontent.com/16081195/107517436-b51b9300-6be8-11eb-9e7b-ac9713e1b5a4.png)

**Comment by ZeroNoRyouki** [comment]
No problems, the feedback is welcome

Yeah that language key is not used. All others behaviors have sub-settings that goes in that red square but not the control rod insertion sensor
