### ISSUE TITLE
Reactor does not turn on after a scram

### ISSUE THREAD

**Issue by AlperBozkir** [ZeroNoRyouki/ExtremeReactors2#35]
For reproduction: Just build a reactor 1x1 fill it and turn it on after reaching full core heat, scram it and try to turn it on again.
The indicator on reactor controller turns yellow but reactor itself is not doing anything.(no power, no heat) Out of 8 different reactors one of them started again with full performance, other one of them started again with like half performance and other 6 of them did not start at all.

**Comment by AlperBozkir** [comment]
Apparently you just have to change control rods' insertion to 0% manually after scramming.

**Comment by ZeroNoRyouki** [comment]
Yup, Scram set all the Control Rods to 100% to stop the Reactor so you need to set them back to something lower than 100% to restart it
