### ISSUE TITLE
strange error/crash after updating Mekanism

### ISSUE THREAD

**Issue by JasonKillsUs** [ZeroNoRyouki/ExtremeReactors2#36]
MC 1.16.5/36.0.42 (ZeroCore2-1.16.4-2.0.20/ExtremeReactors2-1.16.4-2.0.22)
I updated Mekkanism today to version 10.0.21.448...
after restarting minecraft i got this crash report
"https://pastebin.com/peA4TQrJ"
not sure where to go with this.
thanks for looking into :-)

**Comment by ZeroNoRyouki** [comment]
It start fine wihout Mekanism indeed, uhm

**Comment by ZeroNoRyouki** [comment]
What mod pack is this?

**Comment by JasonKillsUs** [comment]
Problem solved, listen to this: i updated fastworkbench mod which uses Mixins instead of registry replacement "fastbenchminusreplacement", "https://www.curseforge.com/minecraft/mc-mods/fastworkbench-minus-replacement"
i restarted MC without any error :-)... weird.

**Comment by JasonKillsUs** [comment]
> 
> 
> What mod pack is this?

no mod pack, just my own collection

**Comment by ZeroNoRyouki** [comment]
Glad that you were able to solve the problem
