### ISSUE TITLE
Some problems with button click

### ISSUE THREAD

**Issue by beiai** [ZeroNoRyouki/ExtremeReactors2#37]
Minecraft Version: 1.16.5
forge: 36.0.42
ExtremeReactors-1.16.4-2.0.22
ZeroCore2-1.16.4-2.0.20

Same problem in #33 
1. All the down buttons in the up and down buttons are having clicking problems
When clicking on the border of the down button, the click can hear the sound, but no response
![2021-02-19_011646](https://user-images.githubusercontent.com/16081195/108394983-45448280-7250-11eb-9528-39a0a41c8f20.png)

2. Outlet Mode / Eject Fuel / Eject Waste buttons in Solid Access Port GUI are having clicking problems
![2021-02-19_012347](https://user-images.githubusercontent.com/16081195/108396029-5cd03b00-7251-11eb-9f37-17b27d328bfc.png)

 I've checked almost all the buttons and there Shouldn't have the same problem anymore.

**Comment by ZeroNoRyouki** [comment]
For the Access Port, the black border is not part of the button. It's just a decoration.

I'll check the up-down controls

**Comment by beiai** [comment]
I don’t want to take the screenshot three times, so I marked it with a red box, which caused some misunderstandings. It’s not the black border. You can try it yourself to easily reproduce the problem

**Comment by ZeroNoRyouki** [comment]
Ah OK. It's probably the same problem as before, the parent panel being a couple pixel too short. Checking it

**Comment by ZeroNoRyouki** [comment]
Yup, 4 pixel short. Fixed it

**Comment by ZeroNoRyouki** [comment]
I've increased a bit the up-down hit boxes. It will be included in the next release

**Comment by ZeroNoRyouki** [comment]
Fixed in ZC 2.0.21 & ER 2.0.23
