### ISSUE TITLE
Config Options dont work

### ISSUE THREAD

**Issue by jajajafeti** [ZeroNoRyouki/ExtremeReactors2#41]
Hey I am playing on ExtremeReactors2-1.16.4-2.0.23 and I wanted to disable the coal to graphite recipie (which I can still do with CT). So I saw in the config `registerCharcoalForSmelting` and `registerCoalForSmelting` and set both to `false`. But nothing changed, its still in JEI and still works in the furnace.

![image](https://user-images.githubusercontent.com/61298096/111920451-566ef200-8a8f-11eb-9afd-457a86bd2a27.png)

**Comment by SonicSpeedster16** [comment]
I can confirm this issue.

Minecraft 1.16.5
Forge 36.1.13
ExtremeReactors2-1.16.4-2.0.23.jar
ZeroCore2-1.16.4-2.0.21.jar

**Comment by TheSnowyChickens** [comment]
Same:

![grafik](https://user-images.githubusercontent.com/29357962/122684006-420fd200-d203-11eb-829c-7d1529afe4d0.png)

**Comment by ZeroNoRyouki** [comment]
Fixed in the next release. I've also added an option to enable/disable the coal block to graphite block smelting/blasting recipes

**Comment by Enterprise12nx01** [comment]
this issue is back, seeing it in verson 1.16.5-2.0.51
