### ISSUE TITLE
question about enigmatica 2 modpack recipes.

### ISSUE THREAD

**Issue by Kuktar** [ZeroNoRyouki/ExtremeReactors2#43]
this might seem redundant and i do realize you manage both mods but i wanted to put it on both mods just in case its a bug or somthing. thank you.

So i just installed enigmatica 2 expert modpack and i updated all mods to most recent version. when i loaded into my server i noticed the recipes were normal and not the expert ones. i started to investigate and went through so many diffrent approaches and found that if i downgrade zerocore2 to version 1.12.2-0.1.2.8 and also i have to downgrade extreme reactors. 

it works just fine with the older version of zerocore2 and extremereactors. I am not even sure whats going on other than maybe some block ids or somthing im not even familer with is happening. i suppose i dont HAVE to have the newest version of extreme reactors but i thought it was odd. thank you for the great mods!

**Comment by ZeroNoRyouki** [comment]
What you are saying is that with older version of ZC / ER the expert recipes worked fine but they do not work with the most recent 1.12.2 versions?

I don't remember changing something on the recipes front in 1.12.2 on my side, I just added a recipe for the new ER in-game book

**Comment by ZeroNoRyouki** [comment]
Have you worked this out?
Thank you
Z
