### ISSUE TITLE
the turbine spins, the steam flows, but who knows where the power goes

### ISSUE THREAD

**Issue by DrBranzz** [ZeroNoRyouki/ExtremeReactors2#45]
I made a turbine using all basic turbine stuff, connected it to a reactor, did everything correct, but the "engage coil" button seems to do nothing but change the apparently arbitrary status of the coils from disengaged to engaged

**Comment by ZeroNoRyouki** [comment]
Do you have actual coil blocks in your Turbine?

**Comment by ZeroNoRyouki** [comment]
Did you sort this out?
Z
