### ISSUE TITLE
getNumberOfControlRods() returns the number of fuel rods

### ISSUE THREAD

**Issue by jontaylor1985** [ZeroNoRyouki/ExtremeReactors2#48]
Looking at the code it appears there is a mistake on line 80 of ExtremeReactors2/src/main/java/it/zerono/mods/extremereactors/gamecontent/multiblock/reactor/computer/ReactorComputerPeripheral.java

This currently causes a reactor with say 15 fuel rods and 5 control rods to return the value 15 when it should be returning the value 5.

The line currently reads

methodConsumer.accept(new ComputerMethod<>("getNumberOfControlRods", wrapControllerValue(IReactorReader::getFuelRodsCount)));

but the method should presumably be reading the IReactorReader::getControlRodsCount

Sorry, I'd create a pull request for you but I have 0 idea how to build minecraft java code and test it.

**Comment by ZeroNoRyouki** [comment]
Fixed in 1.16.5-2.0.24
