### ISSUE TITLE
Old bug is back? Power stored not giving correct redstone signal.

### ISSUE THREAD

**Issue by Novtalath** [ZeroNoRyouki/ExtremeReactors2#49]
I believe old bug back where redstone port set to give Redstone Signal (RS) depending on power buffer inside reactor is always giving RS=15.
![obraz](https://user-images.githubusercontent.com/13785880/127892463-114a0025-3bbe-49ee-ab07-33bbfd35bc61.png)
![obraz](https://user-images.githubusercontent.com/13785880/127892519-c038d90f-1446-4ed7-86e0-2070536b2679.png)
Seems similar issue to this one:
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/4

Mod ver: ExtremeReactors2-1.16.4-2.0.23

**Comment by ZeroNoRyouki** [comment]
Sorry for the late reply. The output of the is always 15 or 0, depending on your condition being meet or not
