### ISSUE TITLE
Water/Steam waste

### ISSUE THREAD

**Issue by Novtalath** [ZeroNoRyouki/ExtremeReactors2#50]
When set up a Reactor<>Turbine system, set it to close loop (do not vent anything) it seems that water conversion to steam loses 12% of water (so water to steam is not 1:1) Also when Steam is used and turned back to water is not 1:1 (using more than 1bucket steam to create 1 bucket of Water). It takes about 12 seconds for system to fully 'dry up' from 122 buckets of water. Tried various pipes and even straight side to side - nothing helps. Wastage happens when converting Water ==> Steam ==> Water

mod ver: ExtremeReactors2-1.16.4-2.0.23

**Comment by ZeroNoRyouki** [comment]
Sorry for the late reply. Yes, there is loss now, it's by design
