### ISSUE TITLE
Updated to architectury-1.22.32-forge.jar and now my reactor has a visual glitch

### ISSUE THREAD

**Issue by manchesterjm** [ZeroNoRyouki/ExtremeReactors2#52]
![Capture](https://user-images.githubusercontent.com/24682863/131262190-1196c3e9-bb56-4f75-9dcd-94ae6e755cf7.JPG)

I am using ExtremeReactors2-1.16.5-2.0.27.jar

**Comment by ZeroNoRyouki** [comment]
Which version of architectury were you using before updating it?

**Comment by manchesterjm** [comment]
1.21.31

**Comment by manchesterjm** [comment]
![Capture](https://user-images.githubusercontent.com/24682863/131263067-839b0052-8a97-4624-b804-3e81cbff76b1.JPG)
Just closed out the game and restarted and now that visual glitch is gone.  I'll close this issue as it seems to have been a glitch.
