### ISSUE TITLE
Reactor does not fill fully

### ISSUE THREAD

**Issue by oliverbaumbach** [ZeroNoRyouki/ExtremeReactors2#53]
Version: ExtremeReactors2-1.16.5-2.0.27 

Steps to reproduce: 
1. Build 3x3 basic reactor with 4,000mB fuel capacity 
2. Insert 8 Yellorite Ingots (500mB each) into solid access port

What happens: 
7 of 8 ingots are consumed, leaving reactor at 3500mB of Fuel. 

What is expected: 
8 ingots are consumed and reactor is 100% filled.

**Comment by ZeroNoRyouki** [comment]
It's by design. Solid Access Ports loose some material while converting solid fuel to liquid (1.16+)

**Comment by oliverbaumbach** [comment]
Wait, but inserting 1 ingot yields 500mB, for each of the 7 ingots consumed. The 8th ingot is _not_ consumed, and left in the solid access port. If it was material conversion loss, then I'd expect all 8 ingots to be consumed, and less than 4,000mB to be within the reactor. As it stands, there is neither material loss nor does the reactor fill correctly.
