### ISSUE TITLE
Issue with modpack transfers

### ISSUE THREAD

**Issue by JakeFromStateFarm101** [ZeroNoRyouki/ExtremeReactors2#60]
continual issue with mod loading when installed through modpack export onto a different computer. here is error log, happens when i release new modpack through export, unsure what is causing this
[crash-2021-11-09_13.38.50-fml.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/7517406/crash-2021-11-09_13.38.50-fml.txt)

**Comment by ZeroNoRyouki** [comment]
I can't reproduce this.

Please check with the lastest version.
