### ISSUE TITLE
Reactor eats all the water returning from the turbine.

### ISSUE THREAD

**Issue by jgilmore** [ZeroNoRyouki/ExtremeReactors2#61]
version 2.0.23 (Yes, slightly out of date. I'm mentioning it only because there's no issue filed.)

Active fluid ports don't work with other active fluid ports when right next to eachother, probably because they don't/won't set to output mode. But of course I can't tell without destroying them, so it's impossible to say if this is really the cause.

Active fluid ports work with a immersive engineering pump between them, but NOT with immersive engineering pipe only. However, all returning coolant vanishes when inserted into reactor. This does NOT happen unless there's a pump, as with just pipe there's no flow.

Passive/active pairs work without pipe (directly connected) but again the coolant vanishes. (The active ports must be set, and then the passive ports set. An odd thing to do as both reactor and turbine need to be built, damaged, and then rebuilt.)

So I've unfortuneately concluded that it's not possible (with only immersive engineering pipes available) to create a working turbine system.

I don't know why the coolant is vanishing. Fixing that would make it possible, but STILL be horrifically clunky to use. See other filed issue.

**Comment by jgilmore** [comment]
I have now confirmed that this issue also exists in 1.6.5-2.0.31, which as of this writing is the latest version I could find.

**Comment by IAteMinecraft** [comment]
it also happens with electrodynamics

**Comment by miiichael** [comment]
Also the 1.16.5-2.0.38 in the Engineer's Life 2 pack.

#76 might be the same bug (where I persuade a turbine to take in steam and not output any fluid in return), though I'm clearly not blaming the reactor there...

**Comment by ZeroNoRyouki** [comment]
Active Ports will not accept fluids/items being inserted into them, you need a Passive port for that. So an active output port can only be connected directly to a passive input port.

You can use the wrench to change the I/O mode of a port while building the multiblock
