### ISSUE TITLE
error when building reprocessor

### ISSUE THREAD

**Issue by IAteMinecraft** [ZeroNoRyouki/ExtremeReactors2#63]
it gives this error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.ShaderInstance.m_173350_(String, Object)" because "$$13" is null
Exit Code: -
[crash-2021-12-07_11.50.28-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/7667309/crash-2021-12-07_11.50.28-client.txt)
1

**Comment by ZeroNoRyouki** [comment]
This should be fixed in the next release of ZeroCore due today
