### ISSUE TITLE
Attempting to login to the world with reactor crashes client

### ISSUE THREAD

**Issue by SpinyOwl** [ZeroNoRyouki/ExtremeReactors2#69]
Minecraft 1.16.5
Forge 36.2.9
ExtremeReactors2: 1.16.5-2.0.31
ZeroCore: 1.16.5-2.1.4

Built a 5x5x5 reactor. Idk what changed, but initially it worked well, but after some time this error occurs after I teleported back to the location with reactor.

[crash-2022-01-01_20.41.00-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/7798171/crash-2022-01-01_20.41.00-client.txt)

**Comment by ZeroNoRyouki** [comment]
Update both mods
