### ISSUE TITLE
JEI compat

### ISSUE THREAD

**Issue by CTH999** [ZeroNoRyouki/ExtremeReactors2#70]
I have a very simple suggestion. Could you please make the machines compatable with JEI? I can't figure out all the recipes for everything, and frankly, I don't want to.

Thanks!

Of course, ultimatly it's your mod

**Comment by ZeroNoRyouki** [comment]
All the machines recipes are already in JEI

**Comment by CTH999** [comment]
I meant the recipes for making the new fuels and such. The recipes _in_ the reprosesor, fluidizer, and so on. What each fuel makes as waste, and, well, that's it.

**Comment by ZeroNoRyouki** [comment]
> I meant the recipes for making the new fuels and such. The recipes _in_ the reprosesor, fluidizer,

They are already there

**Comment by CTH999** [comment]
Really? I tried to get the recipe of that magenta one, the green one, and the cyan one, I pressed "r" and got nothing. I pressed "U" (Uses) on the reactor, the fluizider, and the reproser, and all of them did nothing. So, maybe it's a bug?

**Comment by ZeroNoRyouki** [comment]
Yes. Reactions (fuel to waste conversions) are not recipes

Try to check the recipe for bluthonium ingots or the usage of the cyanite ones

**Comment by CTH999** [comment]
Hmm... the blutonium ingot one and cyanite one does work. But, for the bluetonium one, it is called "**compat.bigreactors.jei.co...**"

Also, you should (consider) putting reactions in as recipes.

**Comment by ZeroNoRyouki** [comment]
> Hmm... the blutonium ingot one and cyanite one does work. But, for the bluetonium one, it is called "**compat.bigreactors.jei.co...**"

I noticed that the other day, already fixed in dev

> Also, you should (consider) putting reactions in as recipes.

They are not recipes because they don't works like recipes. It's not like "crafting" a cynate ingot from a yellorium ingot

> Finally, when you hit "U" on the controller, it should show all recipies the machine is capable of. It's just a simple Quality of Life thing, you can see an example if you hit "U" on a crafting table, it shows all recipes it can do

That's look like a good idea. I'll check it

**Comment by CTH999** [comment]
> > Hmm... the blutonium ingot one and cyanite one does work. But, for the bluetonium one, it is called "**compat.bigreactors.jei.co...**"
> 
> I noticed that the other day, already fixed in dev
> 
> > Also, you should (consider) putting reactions in as recipes.
> 
> They are not recipes because they don't works like recipes. It's not like "crafting" a cynate ingot from a yellorium ingot
> 
> > Finally, when you hit "U" on the controller, it should show all recipies the machine is capable of. It's just a simple Quality of Life thing, you can see an example if you hit "U" on a crafting table, it shows all recipes it can do
> 
> That's look like a good idea. I'll check it

Great! Another thing is considering putting the recipes the things are used for, as well as what fuels turn into what products in the reactor

**Comment by ZeroNoRyouki** [comment]
Which things?

The second part is pretty obvious already, yellorium fuel <> yellorium ingots/blocks etc

**Comment by CTH999** [comment]
I meant like "I put yellorium in, the waste will be..."
"I put bluetonium in, the waste will be ..."
I put (Whatever new fuels), the waste will be...
