### ISSUE TITLE
[1.18.1] Uranium, even though it can be used as a solid fuel, cannot be used in the fluidizer.

### ISSUE THREAD

**Issue by ArchieBeepBoop** [ZeroNoRyouki/ExtremeReactors2#72]
In the latest release of ER2 as of this post, (ExtremeReactors2-1.18.1-2.0.38.jar) while you are able to use solid uranium as solid fuel to input into a reactor directly, the fluidizer will not recognize it (forge:ingots/uranium or forge:storage_blocks/uranium) to turn it into yellorium liquid fuel.

I assume yellorium/uranium are the same thing as both can be used in any recipes that involve them, correct me if I'm wrong.

**Comment by ZeroNoRyouki** [comment]
Yes, you need Yellorium ingots in the Fluidizer (it's a balancing factor for Verderium).

If a mod pack disable yellorite generation, it can add alternative fluidizer recipes
