### ISSUE TITLE
Reactors violate the laws of conservation of (fuel) mass.

### ISSUE THREAD

**Issue by miiichael** [ZeroNoRyouki/ExtremeReactors2#74]
Just built a 3x3x3 (interior) reactor, reported capacity 48B. I feed it 32 ingots.
![image](https://user-images.githubusercontent.com/4179353/154478471-981fd674-e93d-4c0c-ab2e-08680544e4c3.png)
I immediately eject the fuel without turning on the reactor. I receive only 24 ingots back. :disappointed: 

forge-1.16.5-36.2.28
ExtremeReactors2-1.16.5-2.0.38, ZeroCore2-1.16.5-2.1.9
ImmersiveEngineering-1.16.5-5.0.7-143 (in case it matters)

**Comment by ZeroNoRyouki** [comment]
Solid / fluid conversions in a Solid Access Port are lossy.

Use the Fluidizer and Fuel Injection Ports for a lossless conversion.
