### ISSUE TITLE
Fuels

### ISSUE THREAD

**Issue by ESimonis** [ZeroNoRyouki/ExtremeReactors2#79]
Fuels need to be better discribed is the manual. I dont know if it is the mod pack all in one or just extreme reactors but there is 0 documentation on what the new fuels do. ex efficency or how to even use them. currently i am making verderium but i dont even know if you can use it as a current fuel. further documentation would be nice

**Comment by ZeroNoRyouki** [comment]
if you enable advanced tooltips in minecraft you will see a toolpit that tellls you if something is a moderator, fuel, coil, etc when you hover on an item
