### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by KingToyoter** [ZeroNoRyouki/ExtremeReactors2#81]
Game crashes when you place a reactor casing/fuel rod inside an air block that has been flagged as "not valid for the Reactor's exterior"/"Only fuel rods can be used here", crash will occur with both basic and reinforced reactors. Updating the multiblock (by breaking a reactor casing block/placing a reactor casing block on the outside of the reactor) before you attempt to fill an air block will allow you to avoid a game crash.
MInecraft version: 1.18.1
Forge version: 39.1.0
Java version: 17.0.1
Crash report has been provided from an instance with only Extreme Reactors and ZeroCore 2 installed, as I had just started testing reasons for the crash.
[crash-2022-05-02_02.10.11-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/8601129/crash-2022-05-02_02.10.11-client.txt)

**Comment by ZeroNoRyouki** [comment]
This should be fixed in the next release of ZeroCore due today
