### ISSUE TITLE
[1.18.2] Crash when trying to build Reprocessor

### ISSUE THREAD

**Issue by ToxinZangoose** [ZeroNoRyouki/ExtremeReactors2#83]
Hello,
I am currently a huge fan of this mod but I ran into a small issue during my playthrough of DireWolf20's 1.18 pack.

When I built the Reprocessor, the book said the dimensions were 3x7x3. I built accordingly and the multi block said the cords for the block on the middle and bottom.

I right clicked it and the message said something like "[cords] block is invalid"
Then it crashed.

Below is the crash log for the instance it happened in,
[crash-2022-05-28_12.29.24-client.txt](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/8800331/crash-2022-05-28_12.29.24-client.txt)

Thank you for an amazing mod, I enjoy the idea of making tons of energy!

**Comment by Peca21** [comment]
Same thing in my modpack. I also have quark mentioned in the crash report, but according to #81 it's not quarks fault.

**Comment by ZeroNoRyouki** [comment]
This should be fixed in the next release of ZeroCore due today
