### ISSUE TITLE
[1.18.2] Enderium blocks cannot be used as a moderator inside the reactor

### ISSUE THREAD

**Issue by MuresanSergiu** [ZeroNoRyouki/ExtremeReactors2#84]
From what I noticed they are registered in the source (ReactorGameData.java) but not actually working
Mod version: ExtremeReactors2-1.18.2-2.0.42.jar in the DW20 1.18 pack

**Comment by MuresanSergiu** [comment]
FTB Industrial Contraptions
This version of it: ftb-industrial-contraptions-1802.1.4-build.141.jar

**Comment by ZeroNoRyouki** [comment]
By the look of it, they don't add that block to the forge:storage_blocks/enderium tag
Maybe they don't want to do it?

**Comment by MuresanSergiu** [comment]
I checked in-game and it does seem to have it. Hmm... maybe it's some sort of editing the modpack is doing

**Comment by ZeroNoRyouki** [comment]
I've checked the last version of IC available on Curse Forge for 1.18.2 and Enderium is not tagged

**Comment by ZeroNoRyouki** [comment]
I'm adding the block to the tag myself. A new release will be probably out today

**Comment by ZeroNoRyouki** [comment]
![image](https://user-images.githubusercontent.com/7107662/171615854-ff8a03a7-b251-438a-8318-34ff0958e101.png)
