### ISSUE TITLE
Minor discrepancies in The Extreme Book

### ISSUE THREAD

**Issue by aharrisw** [ZeroNoRyouki/ExtremeReactors2#91]
**Version**: ExtremeReactors2-1.18.2-2.0.45

1. The Fluidizer Output Port part page has an image of the Power out port instead

![fluidizer_output_image](https://user-images.githubusercontent.com/10736665/174933786-83c5a58d-a1bc-4799-9fac-70a84fb7780f.png)

2. The Reprocessor Collector part page says their is a GUI however there isn't

![reprocessor_collector_gui](https://user-images.githubusercontent.com/10736665/174933794-028e0b19-3cc1-43b2-ae79-4d1ef4f11751.png)

**Comment by ZeroNoRyouki** [comment]
Thank you!
Fixed in dev
