### ISSUE TITLE
[Bug] FTB Industrial Contraptions blocks missing as Moderator Pt2

### ISSUE THREAD

**Issue by TheonlyTazz** [ZeroNoRyouki/ExtremeReactors2#92]
**Modpack**
Direwolf20 1.18

**Modpack version**
1.5.1

Mod version:
ExtremeReactors2-1.18-2.0.45

All FTBIC Storage Blocks, with exception of Enderium are still not able to being used as Moderator blocks

Note, this is a follow up of a previous issue
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/84

and issues on the FTB-Modpack Github 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/991

**Comment by ZeroNoRyouki** [comment]
They need to add their blocks to the correct forge:/storage_block/<material> tag

**Comment by TheonlyTazz** [comment]
> They need to add their blocks to the correct forge:storage_block/ tag
we have the blocks tagged, that was one of the first things i checked
![image](https://user-images.githubusercontent.com/3908847/175026260-e6697a39-5f96-497a-aa8b-00e1fd9ba481.png)

**Comment by ZeroNoRyouki** [comment]
You tagged the items but not the blocks. 

Moderators are in-world blocks so the block tags are checked. The tooltip is displayed on items but that's me doing it so player can see it in inventories.

**Comment by MaxNeedsSnacks** [comment]
FTBIC as a whole originally was designed for FTB Ultimate — Anniversary Edition by Lat, and Lat is... notoriously not terribly good at designing systems with other mods adding onto them in mind, so the entire energy system might be a little janky :P Whatever you may need tho, I should hopefully be able to change about Zaps
