### ISSUE TITLE
Multiblock Contruction Issue- Control Rods

### ISSUE THREAD

**Issue by BrandonJ98** [ZeroNoRyouki/ExtremeReactors2#96]
When building a maximum size reactor (32x32x48) or anything close to it, I am repeatedly getting the error "Control rods may only be on one face of the reactor" when building, while the control rods were placed in the top face. To fix this, I placed the control rods in the floor instead. It accepted that, however now it is saying the machine is too large and can be at most 32 blocks. The machine is exactly 32x32x48. It should not be too large. When reloading the chunks, the structure appears to build, I have access to the solid access ports, and the charging port. When clicking the controller I still get the message that it is too big. I completely reloaded the world and restarted the modpack, and it works fine.

Modpack: Ragnamod VI
Minecraft version: 1.16.5
Extreme Reactors version: 2.0.41

**Comment by ZeroNoRyouki** [comment]
Should be fixed in ZC 2.1.23+
