### ISSUE TITLE
Separate Texture Assets for GUI Buttons [Suggestion]

### ISSUE THREAD

**Issue by CyanideX** [ZeroNoRyouki/ExtremeReactors2#97]
Would it be possible to get texture assets for the GUI buttons instead of them being hard coded? I would love to add mod support for my Unity and Unity Dark packs but it's not possible at the moment.

![image](https://user-images.githubusercontent.com/3106700/188549451-c224b340-5559-4c93-a311-609d8be6e5e8.png)

**Comment by ZeroNoRyouki** [comment]
The problem with doing that is that all the controls in my GUI framework are designed to be rendered (and used) with arbitrary sizes (fixed, suggested, computed from their parent control layout and content or their own content, etc) and being able to keep doing so with textures would require dropping "effects" like the 3D shadow or the "hover" highlighting and having something like 6 textures per button state

**Comment by CyanideX** [comment]
I understand completely; it's efficient! Unfortunately, it makes it very difficult for resource packs to offer support for mods when buttons are hardcoded. 😅 Is there any possibility of putting some color config options somewhere that I could access, preferably with a gradient toggle?

**Comment by ZeroNoRyouki** [comment]
I think that it's possibile, I just need to find an elegant way to do implement it so that this could be used by other mods too. I'll take a look this weekend

**Comment by ZeroNoRyouki** [comment]
Would you be able to replace a json file from my assets with one with your colours?

**Comment by ZeroNoRyouki** [comment]
Where you able to check out?

**Comment by CyanideX** [comment]
Sorry, it's been a very busy past few months for me. I completely forgot to reply.

> Would you be able to replace a json file from my assets with one with your colours?

Yes, that would work as long as I could remove the gradient. 🙂 Is there a new build for me to test that with?

**Comment by ZeroNoRyouki** [comment]
[gui.zip](https://github.com/ZeroNoRyouki/ExtremeReactors2/files/10325884/gui.zip)

Here you go. The build is for 1.16.5

The file you need to override is er_gui_theme.json, in main resources folder of ER (bigreactors:er_gui_theme.json). 
The is also a .md file with a description of the content of the json file,

You will be able to modify every colour used by all the GUI screens and controls in ER.

**Comment by ZeroNoRyouki** [comment]
I've just pushed up ZeroCore 2.1.28 and ER 2.0.57 for 1.16.5. They contains an updated version of what I've sent you before (along with a couple of fixes in some drawing primitives). I've tested them with a resource pack and all works fine
