### ISSUE TITLE
Using copper blocks as the internal coolant modifier

### ISSUE THREAD

**Issue by GarlicButter2507** [ZeroNoRyouki/ExtremeReactors2#98]
Hello,
My reactor recently de-constructed itself as I used copper blocks as the internal cooling block. The reason for the de-construction was because they oxidized over time and the oxidised version of the block doesn't seem to be a valid coolant (according to the advanced tooltips). I took out all the oxidised copper blocks and was going to replace with waxed copper blocks but these also aren't a valid coolant (according to the advanced tooltips).

I have 2 extreme reactors setup, one small basic one with no reactor glass (which has been fine, i.e the copper hasn't oxidised) and one large reinforced one with glass side walls whereby the copper has oxidised. I'm not sure if this is mean't to happen to deter people from using copper in reinforced reactors or if it is an issue.

Would be interested in hearing your thoughts!

Also, is there any information anywhere regarding the internal modifiers (passive coolant) and whats the best one to use etc? I'm aware that the rarer the resource the better it is, i.e iron blocks are worse than diamond blocks. And diamond blocks are worse than netherite blocks. But it would be good to have a bit more information about all the options (from other mods too) in its Patchouli book maybe?

Great mod otherwise, thanks for bringing back a well loved mod :)

Thanks, Joe
![2022-09-09_08 38 47](https://user-images.githubusercontent.com/67052990/189327105-2c0f952e-dc42-4409-a9c1-fb6a9c1fa0bb.png)

**Comment by ZeroNoRyouki** [comment]
They way I see it, oxidised copper is not a "copper" anymore so it will not be used as a moderator while the reactor is assembled and will give you an error when the reactor is rebuilt
